/* ===================================================
   Jayco — Owner's Manuals
   ---------------------------------------------------
   PROVENANCE. Every row harvested from jayco.com's own
   manual library on 2026-09-07, across all eleven model
   years it publishes (2017-2027). Nothing here is
   written from memory:

     • name, years and the PDF come from the year pages
       (/manuals/?RvManualSearch[year]=YYYY).
     • types come from Jayco's OWN type filter — each
       type was fetched separately and the manuals it
       returned were tagged with it. No model name was
       mapped to a class by guesswork.

   TWO FIELDS ARE ARRAYS, and both for real reasons.

   • types, because one manual covers several classes.
     The 2027 towable manual answers for travel
     trailers, fifth wheels, toy haulers and
     destination trailers alike.

   • years, because a document can be listed under
     more than one. The Renogy lithium manual sits
     under 2022, 2023 and 2024, and picking one of them
     would file it wrongly under the other two.

   THE TAXONOMY IS JAYCO'S, NOT THE 2027 LINEUP'S.
   These manuals reach back to models the current
   catalogue no longer carries — Designer, Hummingbird,
   Octane, Embark — so the type names here are the ones
   Jayco tags manuals with rather than the category ids
   in models-data.js. Forcing them into the current
   eight would have meant inventing a home for coaches
   that no longer have one.

   THE PDF LINKS ARE ABSOLUTE, and point at jayco.com.
   This repo hosts no manuals; these are the real files.
   =================================================== */
window.JAYCO_MANUALS = (function () {
  'use strict';

  return [
    { name: 'Jayco Motorized Class A Owner\'s Manuals', years: [2027], kind: 'Owner\'s Manual',
      types: ['Class A Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/655-Jayco-A---Book-MY27.pdf',
      cover: '../assets/manuals/library/655-class-a-cover-image.webp', coverW: 300, coverH: 195 },
    { name: 'Jayco Motorized Class B Owner\'s Manuals', years: [2027], kind: 'Owner\'s Manual',
      types: ['Class B Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/656-Jayco-B---Book-MY27.pdf',
      cover: '../assets/manuals/library/656-class-b-cover-image.webp', coverW: 300, coverH: 195 },
    { name: 'Jayco Motorized Class C Owner\'s Manuals', years: [2027], kind: 'Owner\'s Manual',
      types: ['Class C Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/657-Jayco-C---Book-MY27.pdf',
      cover: '../assets/manuals/library/657-class-c-cover-image.webp', coverW: 300, coverH: 195 },
    { name: 'Jayco Motorized Super C Owner\'s Manuals', years: [2027], kind: 'Owner\'s Manual',
      types: ['Class C Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/658-Jayco-Super-C---Book-MY27.pdf',
      cover: '../assets/manuals/library/658-super-c-cover-image.webp', coverW: 300, coverH: 195 },
    { name: 'Jayco Towable Owners Manual', years: [2027], kind: 'Owner\'s Manual',
      types: ['Destination Trailers', 'Fifth Wheels', 'Toy Haulers', 'Travel Trailers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/659-Towable-Manual---Book-2027.pdf',
      cover: '../assets/manuals/library/659-towable-manual-2027.webp', coverW: 300, coverH: 195 },
    { name: 'Jayco Towable Warranty Manual', years: [2027], kind: 'Warranty Guide',
      types: ['Destination Trailers', 'Fifth Wheels', 'Toy Haulers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/660-2027-Jayco-Warranty-Guide---Web.pdf',
      cover: '../assets/manuals/library/660-xxx-towable-warranty.webp', coverW: 300, coverH: 390 },
    { name: 'Jayco Class A Owners Manual', years: [2026], kind: 'Owner\'s Manual',
      types: ['Class A Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/651-2026-Jayco-A-Manual---WEB.pdf',
      cover: '../assets/manuals/library/651-screenshot-2026-02-17-094233.webp', coverW: 300, coverH: 391 },
    { name: 'Jayco Class B Owners Manual', years: [2026], kind: 'Owner\'s Manual',
      types: ['Class B Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/652-2026-Jayco-B-Manual-Vs2---WEB.pdf',
      cover: '../assets/manuals/library/652-screenshot-2026-02-17-094452.webp', coverW: 300, coverH: 391 },
    { name: 'Jayco Class C Owners Manual', years: [2026], kind: 'Owner\'s Manual',
      types: ['Class C Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/653-2026-Jayco-C-Manual-Vs2---WEB.pdf',
      cover: '../assets/manuals/library/653-screenshot-2026-02-17-095008.webp', coverW: 300, coverH: 388 },
    { name: 'Jayco Super Class C Owners Manual', years: [2026], kind: 'Owner\'s Manual',
      types: ['Class C Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/654-2026-Jayco-Super-C-Manual-Vs2---WEB.pdf',
      cover: '../assets/manuals/library/654-screenshot-2026-02-17-095104.webp', coverW: 300, coverH: 391 },
    { name: 'Jayco Towable Owners Manual', years: [2026], kind: 'Owner\'s Manual',
      types: ['Destination Trailers', 'Fifth Wheels', 'Toy Haulers', 'Travel Trailers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/645-Jayco-Family-Towable-Manual-Vs2---2026---WEB.pdf',
      cover: '../assets/manuals/library/645-jayco-family-towable-manual-vs2-2026-web-1.webp', coverW: 300, coverH: 390 },
    { name: 'Jayco Towable Warranty Guide', years: [2026], kind: 'Warranty Guide',
      types: ['Destination Trailers', 'Fifth Wheels', 'Toy Haulers', 'Travel Trailers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/648-2026-Jayco-Warranty-Guide---WEB-VS2.pdf',
      cover: '../assets/manuals/library/648-2026-jayco-warranty-guide-web-vs2-cover.webp', coverW: 300, coverH: 390 },
    { name: 'Jayco Class A Owners Manual', years: [2025], kind: 'Owner\'s Manual',
      types: ['Class A Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/640-2025-Jayco-A-Manual---WEB-REDUCED.pdf',
      cover: '../assets/manuals/library/640-2025-jayco-class-a-owners-manual.webp', coverW: 300, coverH: 388 },
    { name: 'Jayco Class B Owners Manual', years: [2025], kind: 'Owner\'s Manual',
      types: ['Class B Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/641-2025-Jayco-B-Manual---WEB-REDUCED.pdf',
      cover: '../assets/manuals/library/641-2025-class-b-owners-manual.webp', coverW: 300, coverH: 390 },
    { name: 'Jayco Class C Owners Manual', years: [2025], kind: 'Owner\'s Manual',
      types: ['Class C Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/642-2025-Jayco-C-Manual---WEB-REDUCED.pdf',
      cover: '../assets/manuals/library/642-2025-class-c-owners-manual.webp', coverW: 300, coverH: 390 },
    { name: 'Jayco Motorized Warranty Guide', years: [2025], kind: 'Warranty Guide',
      types: ['Class A Motorhomes', 'Class B Motorhomes', 'Class C Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/644-2025-Jayco-Motorized-Warranty-Guide---WEB-REDUCED.pdf',
      cover: '../assets/manuals/library/644-25motorizedwarranty.webp', coverW: 300, coverH: 392 },
    { name: 'Jayco Super C Owners Manual', years: [2025], kind: 'Owner\'s Manual',
      types: ['Class C Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/643-2025-Jayco-Super-C-Manual---WEB-REDUCED.pdf',
      cover: '../assets/manuals/library/643-2025-super-c-owners-manual.webp', coverW: 300, coverH: 392 },
    { name: 'Jayco Towable Owners Manual', years: [2025], kind: 'Owner\'s Manual',
      types: ['Destination Trailers', 'Fifth Wheels', 'Toy Haulers', 'Travel Trailers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/636-Jayco-Family-Towable-Manual---2025---WEB-REV-A-041224-REDUCED.pdf',
      cover: '../assets/manuals/library/636-owner-manual.webp', coverW: 300, coverH: 392 },
    { name: 'Jayco Towable Warranty Guide', years: [2025], kind: 'Warranty Guide',
      types: ['Destination Trailers', 'Fifth Wheels', 'Toy Haulers', 'Travel Trailers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/637-2025-Warranty-Guide---Jayco.pdf',
      cover: '../assets/manuals/library/637-warranty.webp', coverW: 300, coverH: 393 },
    { name: 'Alante Manual', years: [2024], kind: 'Owner\'s Manual',
      types: ['Class A Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/623-2024-Jayco-Alante-OM---COLOR.pdf',
      cover: '../assets/manuals/library/623-24alanteom.webp', coverW: 300, coverH: 413 },
    { name: 'Class B Renogy Lithium System Operation Manual', years: [2022, 2023, 2024], kind: 'Component Manual',
      types: ['Class B Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/618-2042257---Renogy-B-Van-Operation-Manual-V7R-11-6-2023.pdf',
      cover: '../assets/manuals/library/618-jm-renogy-manual.webp', coverW: 300, coverH: 392 },
    { name: 'Greyhawk Manual', years: [2024], kind: 'Owner\'s Manual',
      types: ['Class C Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/624-2024-Jayco-Greyhawk-OM---COLOR.pdf',
      cover: '../assets/manuals/library/624-24greyhawkom.webp', coverW: 300, coverH: 413 },
    { name: 'Melbourne & Melbourne Prestige Manual', years: [2024], kind: 'Owner\'s Manual',
      types: ['Class C Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/625-2024-Jayco-Melbourne---Melbourne-Prestige-OM---COLOR.pdf',
      cover: '../assets/manuals/library/625-24melbourne-melbourneprestigeom.webp', coverW: 300, coverH: 413 },
    { name: 'Precept & Precept Prestige Manual', years: [2024], kind: 'Owner\'s Manual',
      types: ['Class A Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/626-2024-Jayco-Precept---Precept-Prestige-OM---COLOR.pdf',
      cover: '../assets/manuals/library/626-24precept-preceptprestigeom.webp', coverW: 300, coverH: 413 },
    { name: 'Redhawk SE and Redhawk Manual', years: [2024], kind: 'Owner\'s Manual',
      types: ['Class C Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/627-2024-Jayco-Redhawk---Redhawk-SE-OM---COLOR.pdf',
      cover: '../assets/manuals/library/627-24redhawkse-redhawkom.webp', coverW: 300, coverH: 413 },
    { name: 'Seneca Prestige Manual', years: [2024], kind: 'Owner\'s Manual',
      types: ['Class C Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/629-2024-Jayco-Seneca-Prestige-OM---COLOR.pdf',
      cover: '../assets/manuals/library/629-24senecaprestigeom.webp', coverW: 300, coverH: 413 },
    { name: 'Seneca XT & Seneca Manual', years: [2024], kind: 'Owner\'s Manual',
      types: ['Class C Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/628-2024-Jayco-Seneca---Seneca-XT-OM---COLOR.pdf',
      cover: '../assets/manuals/library/628-24senecasenecaxtom.webp', coverW: 300, coverH: 413 },
    { name: 'Solstice Li Manual', years: [2024], kind: 'Owner\'s Manual',
      types: ['Class B Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/630-2024-Jayco-Solstice-Li-OM---COLOR.pdf',
      cover: '../assets/manuals/library/630-24solsticeliom.webp', coverW: 300, coverH: 413 },
    { name: 'Solstice Manual', years: [2024], kind: 'Owner\'s Manual',
      types: ['Class B Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/631-2024-Jayco-Solstice-OM---COLOR.pdf',
      cover: '../assets/manuals/library/631-24solsticeom.webp', coverW: 300, coverH: 413 },
    { name: 'Swift Li Manual', years: [2024], kind: 'Owner\'s Manual',
      types: ['Class B Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/632-2024-Jayco-Swift-Li-OM---COLOR.pdf',
      cover: '../assets/manuals/library/632-24swiftliom.webp', coverW: 300, coverH: 413 },
    { name: 'Swift Manual', years: [2024], kind: 'Owner\'s Manual',
      types: ['Class B Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/633-2024-Jayco-Swift-OM---COLOR.pdf',
      cover: '../assets/manuals/library/633-24swiftom.webp', coverW: 300, coverH: 413 },
    { name: 'Terrain Manual', years: [2024], kind: 'Owner\'s Manual',
      types: ['Class B Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/634-2024-Jayco-Terrain-OM---COLOR.pdf',
      cover: '../assets/manuals/library/634-24terrainom.webp', coverW: 300, coverH: 413 },
    { name: 'Towable Owner\'s Manual', years: [2024], kind: 'Owner\'s Manual',
      types: ['Fifth Wheels', 'Toy Haulers', 'Travel Trailers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/619-Jayco-Family-Towable-Manual---2024---WEB.pdf',
      cover: '../assets/manuals/library/619-27.webp', coverW: 300, coverH: 392 },
    { name: 'Towable Warranty Guide', years: [2024], kind: 'Warranty Guide',
      types: ['Fifth Wheels', 'Toy Haulers', 'Travel Trailers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/620-2024-Warranty-Guide---Jayco---WEB.pdf',
      cover: '../assets/manuals/library/620-28.webp', coverW: 300, coverH: 392 },
    { name: 'Alante Owner\'s Manual', years: [2023], kind: 'Owner\'s Manual',
      types: ['Class A Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/587-2023-Jayco-Alante-OM.pdf',
      cover: '../assets/manuals/library/587-alante23om.webp', coverW: 300, coverH: 392 },
    { name: 'Eagle Fifth Wheels Manual', years: [2023], kind: 'Owner\'s Manual',
      types: ['Fifth Wheels'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/609-2023-Jayco-Eagle-FW-OM.pdf',
      cover: '../assets/manuals/library/609-1.webp', coverW: 300, coverH: 392 },
    { name: 'Eagle Travel Trailers Manual', years: [2023], kind: 'Owner\'s Manual',
      types: ['Travel Trailers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/616-2023-Jayco-Eagle-TT-OM.pdf',
      cover: '../assets/manuals/library/616-8.webp', coverW: 300, coverH: 392 },
    { name: 'Embark Owner\'s Manual', years: [2023], kind: 'Owner\'s Manual',
      types: ['Class A Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/588-2023-Jayco-Embark-OM.pdf',
      cover: '../assets/manuals/library/588-embark23om.webp', coverW: 300, coverH: 392 },
    { name: 'Greyhawk Owner\'s Manual', years: [2023], kind: 'Owner\'s Manual',
      types: ['Class C Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/589-2023-Jayco-Greyhawk-OM.pdf',
      cover: '../assets/manuals/library/589-greyhawn23om.webp', coverW: 300, coverH: 392 },
    { name: 'Jay Feather Manual', years: [2023], kind: 'Owner\'s Manual',
      types: ['Travel Trailers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/612-2023-Jayco-JayFeather-OM.pdf',
      cover: '../assets/manuals/library/612-4.webp', coverW: 300, coverH: 392 },
    { name: 'Jay Flight Bungalow Manual', years: [2023], kind: 'Owner\'s Manual',
      types: ['Travel Trailers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/617-2023-Jayco-JayFlight-Bungalow-OM.pdf',
      cover: '../assets/manuals/library/617-9.webp', coverW: 300, coverH: 392 },
    { name: 'Jay Flight Manual', years: [2023], kind: 'Owner\'s Manual',
      types: ['Travel Trailers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/615-2023-Jayco-JayFlight-OM.pdf',
      cover: '../assets/manuals/library/615-7.webp', coverW: 300, coverH: 392 },
    { name: 'Melbourne and Melbourne Prestige Owner\'s Manual', years: [2023], kind: 'Owner\'s Manual',
      types: ['Class C Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/590-2023-Jayco-Melbourne-OM.pdf',
      cover: '../assets/manuals/library/590-melbourne23om.webp', coverW: 300, coverH: 392 },
    { name: 'North Point Manual', years: [2023], kind: 'Owner\'s Manual',
      types: ['Fifth Wheels'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/613-2023-Jayco-NorthPoint-FW-OM.pdf',
      cover: '../assets/manuals/library/613-5.webp', coverW: 300, coverH: 392 },
    { name: 'North Point Owner\'s Manual', years: [2023], kind: 'Owner\'s Manual',
      types: ['Fifth Wheels'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/603-2023-Jayco-NorthPoint-FW-Color-OM.pdf',
      cover: '../assets/manuals/library/603-np-om.webp', coverW: 300, coverH: 461 },
    { name: 'Pinnacle Manual', years: [2023], kind: 'Owner\'s Manual',
      types: ['Fifth Wheels'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/614-2023-Jayco-Pinnacle-FW-OM.pdf',
      cover: '../assets/manuals/library/614-6.webp', coverW: 300, coverH: 392 },
    { name: 'Pinnacle Owner\'s Manual', years: [2023], kind: 'Owner\'s Manual',
      types: ['Fifth Wheels'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/604-2023-Jayco-Pinnacle-FW-Color-OM.pdf',
      cover: '../assets/manuals/library/604-pinna-om.webp', coverW: 300, coverH: 460 },
    { name: 'Precept and Precept Prestige Owner\'s Manual', years: [2023], kind: 'Owner\'s Manual',
      types: ['Class A Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/591-2023-Jayco-Precept-Color-OM.pdf',
      cover: '../assets/manuals/library/591-precept23om.webp', coverW: 300, coverH: 392 },
    { name: 'Redhawk SE and Redhawk Owner\'s Manual', years: [2023], kind: 'Owner\'s Manual',
      types: ['Class C Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/592-2023-Jayco-Redhawk-OM.pdf',
      cover: '../assets/manuals/library/592-redhawk23om.webp', coverW: 300, coverH: 392 },
    { name: 'Seismic Manual', years: [2023], kind: 'Owner\'s Manual',
      types: ['Toy Haulers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/611-2023-Jayco-Seismic-Luxury-FW-OM.pdf',
      cover: '../assets/manuals/library/611-3.webp', coverW: 300, coverH: 392 },
    { name: 'Seismic Owner\'s Manual', years: [2023], kind: 'Owner\'s Manual',
      types: ['Toy Haulers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/605-2023-Jayco-Seismic-Seismic-Luxury-FW-Color-OM.pdf',
      cover: '../assets/manuals/library/605-seismic-om.webp', coverW: 300, coverH: 463 },
    { name: 'Seneca Owner\'s Manual', years: [2023], kind: 'Owner\'s Manual',
      types: ['Class C Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/593-2023-Jayco-Seneca-OM.pdf',
      cover: '../assets/manuals/library/593-seneca23om.webp', coverW: 300, coverH: 392 },
    { name: 'Seneca Prestige Owner\'s Manual', years: [2023], kind: 'Owner\'s Manual',
      types: ['Class C Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/594-2023-Jayco-Seneca-Prestige-OM.pdf',
      cover: '../assets/manuals/library/594-senecaprestige23om.webp', coverW: 300, coverH: 392 },
    { name: 'Swift Li Owner\'s Manual', years: [2023], kind: 'Owner\'s Manual',
      types: ['Class B Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/596-2023-Jayco-Swift-Li-OM.pdf',
      cover: '../assets/manuals/library/596-swiftli23om.webp', coverW: 300, coverH: 392 },
    { name: 'Swift Owner\'s Manual', years: [2023], kind: 'Owner\'s Manual',
      types: ['Class B Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/595-2023-Jayco-Swift-OM.pdf',
      cover: '../assets/manuals/library/595-swift23om.webp', coverW: 300, coverH: 392 },
    { name: 'Terrain Owner\'s Manual', years: [2023], kind: 'Owner\'s Manual',
      types: ['Class B Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/597-2023-Jayco-Terrain-OM.pdf',
      cover: '../assets/manuals/library/597-terrain23om.webp', coverW: 300, coverH: 392 },
    { name: 'White Hawk Manual', years: [2023], kind: 'Owner\'s Manual',
      types: ['Travel Trailers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/610-2023-Jayco-WhiteHawk-OM.pdf',
      cover: '../assets/manuals/library/610-2.webp', coverW: 300, coverH: 392 },
    { name: 'White Hawk Owner\'s Manual', years: [2023], kind: 'Owner\'s Manual',
      types: ['Travel Trailers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/606-2023-Jayco-WhiteHawk-Color-OM.pdf',
      cover: '../assets/manuals/library/606-wh-om.webp', coverW: 300, coverH: 467 },
    { name: 'Alante Owner\'s Manual', years: [2022], kind: 'Owner\'s Manual',
      types: ['Class A Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/555-2022-Jayco-Alante-OM.pdf',
      cover: '../assets/manuals/library/555-22alanteom.webp', coverW: 300, coverH: 392 },
    { name: 'Eagle Fifth Wheel Owner\'s Manual', years: [2022], kind: 'Owner\'s Manual',
      types: ['Fifth Wheels'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/563-2022-Jayco-Eagle-FW-OM.pdf',
      cover: '../assets/manuals/library/563-9.webp', coverW: 300, coverH: 392 },
    { name: 'Eagle Travel Trailer Owner\'s Manual', years: [2022], kind: 'Owner\'s Manual',
      types: ['Travel Trailers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/564-2022-Jayco-Eagle-TT-OM.pdf',
      cover: '../assets/manuals/library/564-8.webp', coverW: 300, coverH: 392 },
    { name: 'Embark Owner\'s Manual', years: [2022], kind: 'Owner\'s Manual',
      types: ['Class A Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/556-2022-Jayco-Embark-OM.pdf',
      cover: '../assets/manuals/library/556-22embarkom.webp', coverW: 300, coverH: 392 },
    { name: 'Greyhawk/Greyhawk Prestige Owner\'s Manual', years: [2022], kind: 'Owner\'s Manual',
      types: ['Class C Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/557-2022-Jayco-Greyhawk-OM.pdf',
      cover: '../assets/manuals/library/557-22greyhawkom.webp', coverW: 300, coverH: 392 },
    { name: 'Jay Feather Owner\'s Manual', years: [2022], kind: 'Owner\'s Manual',
      types: ['Travel Trailers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/565-2022-Jayco-Jay-Feather-OM.pdf',
      cover: '../assets/manuals/library/565-7.webp', coverW: 300, coverH: 392 },
    { name: 'Jay Flight Bungalow Owner\'s Manual', years: [2022], kind: 'Owner\'s Manual',
      types: ['Travel Trailers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/566-2022-Jayco-JayFlight-Bungalow-OM.pdf',
      cover: '../assets/manuals/library/566-10.webp', coverW: 300, coverH: 392 },
    { name: 'Jay Flight Octane Owner\'s Manual', years: [2022], kind: 'Owner\'s Manual',
      types: ['Toy Haulers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/567-2022-Jayco-JayFlight-Octane-OM.pdf',
      cover: '../assets/manuals/library/567-4.webp', coverW: 300, coverH: 392 },
    { name: 'Jay Flight Owner\'s Manual', years: [2022], kind: 'Owner\'s Manual',
      types: ['Travel Trailers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/568-2022-Jayco-Jay-Flight-OM.pdf',
      cover: '../assets/manuals/library/568-6.webp', coverW: 300, coverH: 392 },
    { name: 'Melbourne/Melbourne Prestige Owner\'s Manual', years: [2022], kind: 'Owner\'s Manual',
      types: ['Class C Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/558-2022-Jayco-Melbourne-OM.pdf',
      cover: '../assets/manuals/library/558-22melbourneom.webp', coverW: 300, coverH: 392 },
    { name: 'North Point Owner\'s Manual', years: [2022], kind: 'Owner\'s Manual',
      types: ['Fifth Wheels'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/569-2022-Jayco-NorthPoint-FW-OM.pdf',
      cover: '../assets/manuals/library/569-5.webp', coverW: 300, coverH: 392 },
    { name: 'Pinnacle Owner\'s Manual', years: [2022], kind: 'Owner\'s Manual',
      types: ['Fifth Wheels'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/570-2022-Jayco-Pinnacle-FW-OM.pdf',
      cover: '../assets/manuals/library/570-3.webp', coverW: 300, coverH: 392 },
    { name: 'Precept/Precept Prestige Owner\'s Manual', years: [2022], kind: 'Owner\'s Manual',
      types: ['Class A Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/559-2022-Jayco-Precept-OM.pdf',
      cover: '../assets/manuals/library/559-22preceptom.webp', coverW: 300, coverH: 392 },
    { name: 'Redhawk SE/Redhawk Owner\'s Manual', years: [2022], kind: 'Owner\'s Manual',
      types: ['Class C Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/560-2022-Jayco-Redhawk-OM.pdf',
      cover: '../assets/manuals/library/560-22redhawkom.webp', coverW: 300, coverH: 392 },
    { name: 'Seismic Owner\'s Manual', years: [2022], kind: 'Owner\'s Manual',
      types: ['Toy Haulers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/571-2022-Jayco-Siesmic-FW-OM.pdf',
      cover: '../assets/manuals/library/571-1.webp', coverW: 300, coverH: 392 },
    { name: 'Seneca/Seneca Prestige Owner\'s Manual', years: [2022], kind: 'Owner\'s Manual',
      types: ['Class C Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/561-2022-Jayco-Seneca-OM.pdf',
      cover: '../assets/manuals/library/561-22senecaom.webp', coverW: 300, coverH: 392 },
    { name: 'Swift Owner\'s Manual', years: [2022], kind: 'Owner\'s Manual',
      types: ['Class B Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/562-2022-Jayco-Swift-OM.pdf',
      cover: '../assets/manuals/library/562-22swiftom.webp', coverW: 300, coverH: 392 },
    { name: 'White Hawk Owner\'s Manual', years: [2022], kind: 'Owner\'s Manual',
      types: ['Travel Trailers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/572-2022-Jayco-WhiteHawk-OM.pdf',
      cover: '../assets/manuals/library/572-2.webp', coverW: 300, coverH: 392 },
    { name: 'Alante Owner\'s Manual', years: [2021], kind: 'Owner\'s Manual',
      types: ['Class A Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/534-2021-Jayco-Alante-OM.pdf',
      cover: '../assets/manuals/library/21alante-61243.webp', coverW: 300, coverH: 392 },
    { name: 'Eagle Fifth Wheel Owner\'s Manual', years: [2021], kind: 'Owner\'s Manual',
      types: ['Fifth Wheels'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/529-2021-Jayco-Eagle-FW-OM.pdf',
      cover: '../assets/manuals/library/eagle-fw1-11507.webp', coverW: 300, coverH: 392 },
    { name: 'Embark Owner\'s Manual', years: [2021], kind: 'Owner\'s Manual',
      types: ['Class A Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/535-2021-Jayco-Embark-OM.pdf',
      cover: '../assets/manuals/library/21embark-61338.webp', coverW: 300, coverH: 392 },
    { name: 'Greyhawk/Greyhawk Prestige Owner\'s Manual', years: [2021], kind: 'Owner\'s Manual',
      types: ['Class C Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/536-2021-Jayco-Greyhawk-OM.pdf',
      cover: '../assets/manuals/library/21greyhawk-61393.webp', coverW: 300, coverH: 392 },
    { name: 'Jay Feather Owner\'s Manual', years: [2021], kind: 'Owner\'s Manual',
      types: ['Travel Trailers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/523-2021-Jayco-JayFeather-OM.pdf',
      cover: '../assets/manuals/library/jay-feather1-11243.webp', coverW: 300, coverH: 392 },
    { name: 'Jay Flight Bungalow Owner\'s Manual', years: [2021], kind: 'Owner\'s Manual',
      types: ['Travel Trailers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/526-2021-Jayco-JayFlight-Bungalow-OM.pdf',
      cover: '../assets/manuals/library/bungalow1-11381.webp', coverW: 300, coverH: 392 },
    { name: 'Jay Flight Octane Owner\'s Manual', years: [2021], kind: 'Owner\'s Manual',
      types: ['Toy Haulers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/527-2021-Jayco-JayFlight-Octane-OM.pdf',
      cover: '../assets/manuals/library/octane-11436.webp', coverW: 300, coverH: 392 },
    { name: 'Jay Flight Owner\'s Manual', years: [2021], kind: 'Owner\'s Manual',
      types: ['Travel Trailers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/525-2021-Jayco-Jay-Flight-OM.pdf',
      cover: '../assets/manuals/library/jay-flight1-11345.webp', coverW: 300, coverH: 392 },
    { name: 'Melbourne/Melbourne Prestige Owner\'s Manual', years: [2021], kind: 'Owner\'s Manual',
      types: ['Class C Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/537-2021-Jayco-Melbourne-OM.pdf',
      cover: '../assets/manuals/library/21melbourne-61460.webp', coverW: 300, coverH: 392 },
    { name: 'North Point Owner\'s Manual', years: [2021], kind: 'Owner\'s Manual',
      types: ['Fifth Wheels'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2021%20Jayco%20NorthPoint%20FW%20OM%20BW.pdf',
      cover: '../assets/manuals/library/north-point-1-11619.webp', coverW: 300, coverH: 392 },
    { name: 'North Point Owner\'s Manual', years: [2021], kind: 'Owner\'s Manual',
      types: ['Fifth Wheels'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2021%20Jayco%20NorthPoint%20FW%20OM%20BW%20RevA.pdf',
      cover: '../assets/manuals/library/north-point-owners-manual-73360.webp', coverW: 300, coverH: 392 },
    { name: 'Pinnacle Owner\'s Manual', years: [2021], kind: 'Owner\'s Manual',
      types: ['Fifth Wheels'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/531-2021-Jayco-Pinnacle-FW-OM.pdf',
      cover: '../assets/manuals/library/pinnacle-1-11675.webp', coverW: 300, coverH: 392 },
    { name: 'Precept/Precept Prestige Owner\'s Manual', years: [2021], kind: 'Owner\'s Manual',
      types: ['Class A Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/538-2021-Jayco-Precept-OM.pdf',
      cover: '../assets/manuals/library/21precept-61547.webp', coverW: 300, coverH: 392 },
    { name: 'Redhawk SE/ Redhawk Owner\'s Manual', years: [2021], kind: 'Owner\'s Manual',
      types: ['Class C Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/539-2021-Jayco-Redhawk-OM.pdf',
      cover: '../assets/manuals/library/21redhawk-61620.webp', coverW: 300, coverH: 392 },
    { name: 'Seismic Owner\'s Manual', years: [2021], kind: 'Owner\'s Manual',
      types: ['Toy Haulers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/532-2021-Jayco-Siesmic-FW-OM.pdf',
      cover: '../assets/manuals/library/seismic1-11707.webp', coverW: 300, coverH: 392 },
    { name: 'Seneca Owner\'s Manual', years: [2021], kind: 'Owner\'s Manual',
      types: ['Class C Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/540-2021-Jayco-Seneca-OM.pdf',
      cover: '../assets/manuals/library/21seneca-95092.webp', coverW: 300, coverH: 392 },
    { name: 'Swift Owner\'s Manual', years: [2021], kind: 'Owner\'s Manual',
      types: ['Class B Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/554-2021-Jayco-Swift-OM.pdf',
      cover: '../assets/manuals/library/554-swift-manual.webp', coverW: 300, coverH: 392 },
    { name: 'Talon Owner\'s Manual', years: [2021], kind: 'Owner\'s Manual',
      types: ['Toy Haulers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/533-2021-Jayco-Talon-FW-OM.pdf',
      cover: '../assets/manuals/library/talon1-11759.webp', coverW: 300, coverH: 392 },
    { name: 'White Hawk Owner\'s Manual', years: [2021], kind: 'Owner\'s Manual',
      types: ['Travel Trailers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/524-2021-Jayco-WhiteHawk-OM.pdf',
      cover: '../assets/manuals/library/white-hawk1-11306.webp', coverW: 300, coverH: 392 },
    { name: 'Alante Owner\'s Manual', years: [2020], kind: 'Owner\'s Manual',
      types: ['Class A Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2020%20Jayco%20Alante%20OM%20BW.pdf',
      cover: '../assets/manuals/library/2020-jayco-alante-om-cover-23027.webp', coverW: 300, coverH: 392 },
    { name: 'Eagle FW Owner\'s Manual', years: [2020], kind: 'Owner\'s Manual',
      types: ['Fifth Wheels'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2020%20Jayco%20Eagle%20FW%20OM%20BW.pdf',
      cover: '../assets/manuals/library/2020-jayco-eagle-fw-om-cover-23126.webp', coverW: 300, coverH: 392 },
    { name: 'Eagle TT Owner\'s Manual', years: [2020], kind: 'Owner\'s Manual',
      types: ['Travel Trailers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2020%20Jayco%20Eagle%20TT%20OM%20BW.pdf',
      cover: '../assets/manuals/library/2020-jayco-eagle-tt-om-cover-23210.webp', coverW: 300, coverH: 392 },
    { name: 'Embark Owner\'s Manual', years: [2020], kind: 'Owner\'s Manual',
      types: ['Class A Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2020%20Jayco%20Embark%20OM%20BW.pdf',
      cover: '../assets/manuals/library/2020-jayco-embark-om-cover-23320.webp', coverW: 300, coverH: 392 },
    { name: 'Greyhawk/ Greyhawk Prestige Owner\'s Manual', years: [2020], kind: 'Owner\'s Manual',
      types: ['Class C Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2020%20Jayco%20Greyhawk%20OM%20BW.pdf',
      cover: '../assets/manuals/library/2020-jayco-greyhawk-om-cover-23452.webp', coverW: 300, coverH: 392 },
    { name: 'Hummingbird Owner\'s Manual', years: [2020], kind: 'Owner\'s Manual',
      types: ['Travel Trailers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2020%20Jayco%20Hummingbird%20OM%20BW.pdf',
      cover: '../assets/manuals/library/2020-jayco-hummingbird-om-cover-22697.webp', coverW: 300, coverH: 392 },
    { name: 'Jay Feather Owner\'s Manual', years: [2020], kind: 'Owner\'s Manual',
      types: ['Travel Trailers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2020%20Jayco%20Jay%20Feather%20OM%20BW.pdf',
      cover: '../assets/manuals/library/2020-jayco-jay-feather-om-cover-23548.webp', coverW: 300, coverH: 392 },
    { name: 'Jay Flight Bungalow Owner\'s Manual', years: [2020], kind: 'Owner\'s Manual',
      types: ['Travel Trailers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2020%20Jayco%20JayFlight%20Bungalow%20OM%20BW.pdf',
      cover: '../assets/manuals/library/2020-jayco-jayflight-bungalow-om-cover-23611.webp', coverW: 300, coverH: 392 },
    { name: 'Jay Flight Owner\'s Manual', years: [2020], kind: 'Owner\'s Manual',
      types: ['Travel Trailers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2020%20Jayco%20JayFlight%20OM%20BW.pdf',
      cover: '../assets/manuals/library/2020-jayco-jayflight-om-cover2-23734.webp', coverW: 300, coverH: 392 },
    { name: 'Melbourne/ Melbourne Prestige Owner\'s Manual', years: [2020], kind: 'Owner\'s Manual',
      types: ['Class C Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2020%20Jayco%20Melbourne%20OM%20BW.pdf',
      cover: '../assets/manuals/library/2020-jayco-melbourne-om-cover-23934.webp', coverW: 300, coverH: 392 },
    { name: 'North Point Owner\'s Manual', years: [2020], kind: 'Owner\'s Manual',
      types: ['Fifth Wheels'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2020%20Jayco%20NorthPoint%20FW%20OM%20BW.pdf',
      cover: '../assets/manuals/library/2020-jayco-northpoint-fw-om-cover-24031.webp', coverW: 300, coverH: 392 },
    { name: 'Octane SL Owner\'s Manual', years: [2020], kind: 'Owner\'s Manual',
      types: ['Toy Haulers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2020%20Jayco%20Octane%20OM%20BW.pdf',
      cover: '../assets/manuals/library/2020-jayco-octane-om-cover-24223.webp', coverW: 300, coverH: 392 },
    { name: 'Pinnacle Owner\'s Manual', years: [2020], kind: 'Owner\'s Manual',
      types: ['Fifth Wheels'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2020%20Jayco%20Pinnacle%20FW%20OM%20BW.pdf',
      cover: '../assets/manuals/library/2020-jayco-pinnacle-fw-om-cover-90904.webp', coverW: 300, coverH: 392 },
    { name: 'Precept/ Precept Prestige Owner\'s Manual', years: [2020], kind: 'Owner\'s Manual',
      types: ['Class A Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2020%20Jayco%20Precept%20OM%20BW.pdf',
      cover: '../assets/manuals/library/2020-jayco-precept-om-cover-24267.webp', coverW: 300, coverH: 392 },
    { name: 'Redhawk/ Redhawk SE Owner\'s Manual', years: [2020], kind: 'Owner\'s Manual',
      types: ['Class C Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2020%20Jayco%20Redhawk%20OM%20BW.pdf',
      cover: '../assets/manuals/library/2020-jayco-redhawk-om-cover-24424.webp', coverW: 300, coverH: 392 },
    { name: 'Seismic Owner\'s Manual', years: [2020], kind: 'Owner\'s Manual',
      types: ['Toy Haulers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2020%20Jayco%20Siesmic%20FW%20OM%20BW.pdf',
      cover: '../assets/manuals/library/2020-jayco-siesmic-fw-om-cover-24623.webp', coverW: 300, coverH: 392 },
    { name: 'Seneca Owner\'s Manual', years: [2020], kind: 'Owner\'s Manual',
      types: ['Class C Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2020%20Jayco%20Seneca%20OM%20BW.pdf',
      cover: '../assets/manuals/library/2020-jayco-seneca-om-cover-24512.webp', coverW: 300, coverH: 392 },
    { name: 'Talon Owner\'s Manual', years: [2020], kind: 'Owner\'s Manual',
      types: ['Toy Haulers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2020%20Jayco%20Talon%20FW%20OM%20BW.pdf',
      cover: '../assets/manuals/library/2020-jayco-talon-fw-om-cover-24718.webp', coverW: 300, coverH: 392 },
    { name: 'White Hawk Owner\'s Manual', years: [2020], kind: 'Owner\'s Manual',
      types: ['Travel Trailers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2020%20Jayco%20Whitehawk%20OM%20BW.pdf',
      cover: '../assets/manuals/library/2020-jayco-whitehawk-om-cover-24810.webp', coverW: 300, coverH: 392 },
    { name: 'Eagle FW Manual', years: [2019], kind: 'Owner\'s Manual',
      types: ['Fifth Wheels'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2019%20Jayco%20Eagle%20FW%20OM%20Color%20RevA.pdf',
      cover: '../assets/manuals/library/eagle-fw-09358.webp', coverW: 300, coverH: 392 },
    { name: 'Eagle TT Manual', years: [2019], kind: 'Owner\'s Manual',
      types: ['Travel Trailers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2019%20Jayco%20Eagle%20TT%20OM%20Color%20RevA.pdf',
      cover: '../assets/manuals/library/eagle-23637.webp', coverW: 300, coverH: 392 },
    { name: 'Hummingbird Manual', years: [2019], kind: 'Owner\'s Manual',
      types: ['Travel Trailers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2019%20Jayco%20Hummingbird%20OM%20Color%20RevA.pdf',
      cover: '../assets/manuals/library/bird-08989.webp', coverW: 300, coverH: 392 },
    { name: 'Jay Feather Manual', years: [2019], kind: 'Owner\'s Manual',
      types: ['Travel Trailers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2019%20Jayco%20Jay%20Feather%20OM%20Color%20RevA.pdf',
      cover: '../assets/manuals/library/feather-09104.webp', coverW: 300, coverH: 392 },
    { name: 'Jay Flight Bungalow Manual', years: [2019], kind: 'Owner\'s Manual',
      types: ['Travel Trailers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2019%20Jayco%20JayFlight%20Bungalow%20OM%20Color%20RevA.pdf',
      cover: '../assets/manuals/library/bung-09461.webp', coverW: 300, coverH: 392 },
    { name: 'Jay Flight Manual', years: [2019], kind: 'Owner\'s Manual',
      types: ['Travel Trailers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2019%20Jayco%20JayFlight%20OM%20Color%20RevA.pdf',
      cover: '../assets/manuals/library/jay-flight-09263.webp', coverW: 300, coverH: 392 },
    { name: 'Jay Sport Manual', years: [2019], kind: 'Owner\'s Manual',
      types: ['Camping Trailers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2019%20Jayco%20Camping%20Trailers%20OM%20Color%20Rev%20A.pdf',
      cover: '../assets/manuals/library/jay-sport-08917.webp', coverW: 300, coverH: 392 },
    { name: 'North Point Manual', years: [2019], kind: 'Owner\'s Manual',
      types: ['Fifth Wheels'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2019%20Jayco%20NorthPoint%20FW%20OM%20Color%20RevA.pdf',
      cover: '../assets/manuals/library/north-point-97456.webp', coverW: 300, coverH: 392 },
    { name: 'Pinnacle Manual', years: [2019], kind: 'Owner\'s Manual',
      types: ['Fifth Wheels'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2019%20Jayco%20Pinnacle%20FW%20OM%20Color%20RevA.pdf',
      cover: '../assets/manuals/library/pinnacle-09403.webp', coverW: 300, coverH: 392 },
    { name: 'Seismic Manual', years: [2019], kind: 'Owner\'s Manual',
      types: ['Toy Haulers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2019%20Jayco%20Siesmic%20FW%20Color%20RevA.pdf',
      cover: '../assets/manuals/library/seismic-09585.webp', coverW: 300, coverH: 392 },
    { name: 'Talon Manual', years: [2019], kind: 'Owner\'s Manual',
      types: ['Toy Haulers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2019%20Jayco%20Talon%20FW%20OM%20Color%20RevA.pdf',
      cover: '../assets/manuals/library/talon-09526.webp', coverW: 300, coverH: 392 },
    { name: 'White Hawk Manual', years: [2019], kind: 'Owner\'s Manual',
      types: ['Travel Trailers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2019%20Jayco%20Whitehawk%20OM%20Color%20RevA.pdf',
      cover: '../assets/manuals/library/white-hawk-09200.webp', coverW: 300, coverH: 392 },
    { name: 'Alante Manual', years: [2018], kind: 'Owner\'s Manual',
      types: ['Class A Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/WEB%202018%20Jayco%20Alante%20OM%20Color%20RevA.pdf',
      cover: '../assets/manuals/library/alante-cover-93055.webp', coverW: 300, coverH: 392 },
    { name: 'Eagle Fifth Wheels Manual', years: [2018], kind: 'Owner\'s Manual',
      types: ['Fifth Wheels'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2018%20Eagle%20FW.pdf',
      cover: '../assets/manuals/library/eagle-fw-20812.webp', coverW: 300, coverH: 392 },
    { name: 'Eagle Travel Trailers Manual', years: [2018], kind: 'Owner\'s Manual',
      types: ['Travel Trailers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2018%20Eagle%20TT.pdf',
      cover: '../assets/manuals/library/eagle-20635.webp', coverW: 300, coverH: 392 },
    { name: 'Greyhawk Manual', years: [2018], kind: 'Owner\'s Manual',
      types: ['Class C Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/WEB%202018%20Jayco%20Greyhawk%20OM%20Color%20RevA.pdf',
      cover: '../assets/manuals/library/greyhawk-cover-93244.webp', coverW: 300, coverH: 392 },
    { name: 'Hummingbird Manual', years: [2018], kind: 'Owner\'s Manual',
      types: ['Travel Trailers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2018%20Hummingbird.pdf',
      cover: '../assets/manuals/library/hummingbird-19266.webp', coverW: 300, coverH: 392 },
    { name: 'Jay Feather Manual', years: [2018], kind: 'Owner\'s Manual',
      types: ['Travel Trailers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2018%20Jay%20Feather.pdf',
      cover: '../assets/manuals/library/jay-feather-20389.webp', coverW: 300, coverH: 392 },
    { name: 'Jay Flight Bungalow Manual', years: [2018], kind: 'Owner\'s Manual',
      types: ['Travel Trailers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2018%20Jay%20Flight%20Bungalow.pdf',
      cover: '../assets/manuals/library/jay-flight-bungalow-20533.webp', coverW: 300, coverH: 392 },
    { name: 'Jay Flight Manual', years: [2018], kind: 'Owner\'s Manual',
      types: ['Travel Trailers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2018%20Jay%20Flight.pdf',
      cover: '../assets/manuals/library/jay-flight-20234.webp', coverW: 300, coverH: 392 },
    { name: 'Jay Sport Manual', years: [2018], kind: 'Owner\'s Manual',
      types: ['Camping Trailers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2018%20Camping%20Trailers.pdf',
      cover: '../assets/manuals/library/jay-sport-19500.webp', coverW: 300, coverH: 392 },
    { name: 'Melbourne Manual', years: [2018], kind: 'Owner\'s Manual',
      types: ['Class C Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/WEB%202018%20Jayco%20Melbourne%20OM%20Color%20RevA.pdf',
      cover: '../assets/manuals/library/melbourne-cover-93297.webp', coverW: 300, coverH: 392 },
    { name: 'North Point Manual', years: [2018], kind: 'Owner\'s Manual',
      types: ['Fifth Wheels'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2018%20North%20Point.pdf',
      cover: '../assets/manuals/library/north-point-17582.webp', coverW: 300, coverH: 392 },
    { name: 'Octane Manual', years: [2018], kind: 'Owner\'s Manual',
      types: ['Toy Haulers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2018%20Octane.pdf',
      cover: '../assets/manuals/library/octane-16743.webp', coverW: 300, coverH: 392 },
    { name: 'Pinnacle Manual', years: [2018], kind: 'Owner\'s Manual',
      types: ['Fifth Wheels'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2018%20Pinnacle.pdf',
      cover: '../assets/manuals/library/pinnacle-00067.webp', coverW: 300, coverH: 392 },
    { name: 'Precept Manual', years: [2018], kind: 'Owner\'s Manual',
      types: ['Class A Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/WEB%202018%20Jayco%20Precept%20OM%20Color%20RevA.pdf',
      cover: '../assets/manuals/library/precept-cover-93333.webp', coverW: 300, coverH: 392 },
    { name: 'Redhawk Manual', years: [2018], kind: 'Owner\'s Manual',
      types: ['Class C Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/WEB%202018%20Jayco%20Redhawk%20OM%20Color%20RevA.pdf',
      cover: '../assets/manuals/library/redhawk-cover-93375.webp', coverW: 300, coverH: 392 },
    { name: 'Seismic Owner\'s Manual', years: [2018], kind: 'Owner\'s Manual',
      types: ['Toy Haulers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2018%20Seismic.pdf',
      cover: '../assets/manuals/library/seismic-20915.webp', coverW: 300, coverH: 392 },
    { name: 'Seneca Manual', years: [2018], kind: 'Owner\'s Manual',
      types: ['Class C Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/TEST%202018%20Jayco%20Seneca%20OM%20Color%20RevA.pdf',
      cover: '../assets/manuals/library/seneca-cover-93630.webp', coverW: 300, coverH: 392 },
    { name: 'Talon Manual', years: [2018], kind: 'Owner\'s Manual',
      types: ['Toy Haulers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2018%20Talon.pdf',
      cover: '../assets/manuals/library/talon-96116.webp', coverW: 300, coverH: 392 },
    { name: 'White Hawk Manual', years: [2018], kind: 'Owner\'s Manual',
      types: ['Travel Trailers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2018%20White%20Hawk.pdf',
      cover: '../assets/manuals/library/white-hawk-96574.webp', coverW: 300, coverH: 392 },
    { name: 'Alante Manual', years: [2017], kind: 'Owner\'s Manual',
      types: ['Class A Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2017%20Jayco%20Alante%20OM%20Black%20and%20White.pdf',
      cover: '../assets/manuals/library/2017-jayco-alante-om-black-and-white-1-02160.webp', coverW: 300, coverH: 392 },
    { name: 'Designer Manual', years: [2017], kind: 'Owner\'s Manual',
      types: ['Fifth Wheels'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2017%20Jayco%20Designer%20FW%20OM%20Black%20and%20White.pdf',
      cover: '../assets/manuals/library/2017-jayco-designer-fw-om-black-and-white-1-02215.webp', coverW: 300, coverH: 392 },
    { name: 'Eagle Fifth Wheels Manual', years: [2017], kind: 'Owner\'s Manual',
      types: ['Fifth Wheels'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2017%20Jayco%20Eagle%20FW%20OM%20Black%20and%20White.pdf',
      cover: '../assets/manuals/library/2017-jayco-eagle-fw-om-black-and-white-1-02234.webp', coverW: 300, coverH: 392 },
    { name: 'Eagle Travel Trailers Manual', years: [2017], kind: 'Owner\'s Manual',
      types: ['Travel Trailers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/RevA_2017%20Jayco%20Eagle%20TT%20OM%20Black%20and%20White.pdf',
      cover: '../assets/manuals/library/reva-2017-jayco-eagle-tt-om-black-and-white-1-02262.webp', coverW: 300, coverH: 392 },
    { name: 'Greyhawk Manual', years: [2017], kind: 'Owner\'s Manual',
      types: ['Class C Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2017%20Jayco%20Greyhawk%20OM%20Black%20and%20White.pdf',
      cover: '../assets/manuals/library/2017-jayco-greyhawk-om-black-and-white-1-02280.webp', coverW: 300, coverH: 392 },
    { name: 'Hummingbird Manual', years: [2017], kind: 'Owner\'s Manual',
      types: ['Travel Trailers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/RevA_2017%20Jayco%20Hummingbird%20OM%20Black%20and%20White.pdf',
      cover: '../assets/manuals/library/reva-2017-jayco-hummingbird-om-black-and-white-1-02297.webp', coverW: 300, coverH: 392 },
    { name: 'Jay Feather Manual', years: [2017], kind: 'Owner\'s Manual',
      types: ['Travel Trailers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/RevA_2017%20Jayco%20JayFeather%20OM%20Black%20and%20White.pdf',
      cover: '../assets/manuals/library/reva-2017-jayco-jayfeather-om-black-and-white-1-02316.webp', coverW: 300, coverH: 392 },
    { name: 'Jay Flight Bungalow Manual', years: [2017], kind: 'Owner\'s Manual',
      types: ['Travel Trailers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2017%20Jayco%20JayFlight%20Bungalow%20OM%20Black%20and%20White.pdf',
      cover: '../assets/manuals/library/2017-jayco-jayflight-bungalow-om-black-and-white-1-02334.webp', coverW: 300, coverH: 392 },
    { name: 'Jay Flight Manual', years: [2017], kind: 'Owner\'s Manual',
      types: ['Travel Trailers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/RevA_2017%20Jayco%20JayFlight%20OM%20Black%20and%20White.pdf',
      cover: '../assets/manuals/library/reva-2017-jayco-jayflight-om-black-and-white-1-02349.webp', coverW: 300, coverH: 392 },
    { name: 'Jay Sport Manual', years: [2017], kind: 'Owner\'s Manual',
      types: ['Camping Trailers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2017%20Jayco%20JaySport%20Camping%20Trailer%20OM%20Black%20and%20White.pdf',
      cover: '../assets/manuals/library/2017-jayco-jaysport-camping-trailer-om-black-and-white-1-02369.webp', coverW: 300, coverH: 392 },
    { name: 'Melbourne Manual', years: [2017], kind: 'Owner\'s Manual',
      types: ['Class C Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2017%20Jayco%20Melbourne%20OM%20Black%20and%20White.pdf',
      cover: '../assets/manuals/library/2017-jayco-melbourne-om-black-and-white-1-02382.webp', coverW: 300, coverH: 392 },
    { name: 'North Point Manual', years: [2017], kind: 'Owner\'s Manual',
      types: ['Fifth Wheels'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2017%20Jayco%20NorthPoint%20FW%20OM_Black%20and%20White.pdf',
      cover: '../assets/manuals/library/2017-jayco-northpoint-fw-om-black-and-white-1-02394.webp', coverW: 300, coverH: 392 },
    { name: 'Octane Manual', years: [2017], kind: 'Owner\'s Manual',
      types: ['Toy Haulers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/RevA_2017%20Jayco%20Octane%20OM%20Black%20and%20White.pdf',
      cover: '../assets/manuals/library/reva-2017-jayco-octane-om-black-and-white-1-02409.webp', coverW: 300, coverH: 392 },
    { name: 'Pinnacle Manual', years: [2017], kind: 'Owner\'s Manual',
      types: ['Fifth Wheels'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2017%20Jayco%20Pinnacle%20OM%20Black%20and%20White.pdf',
      cover: '../assets/manuals/library/2017-jayco-pinnacle-om-black-and-white-1-02428.webp', coverW: 300, coverH: 392 },
    { name: 'Precept Manual', years: [2017], kind: 'Owner\'s Manual',
      types: ['Class A Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2017%20Jayco%20Precept%20OM%20%20Black%20and%20White.pdf',
      cover: '../assets/manuals/library/2017-jayco-precept-om-black-and-white-1-02441.webp', coverW: 300, coverH: 392 },
    { name: 'Redhawk Manual', years: [2017], kind: 'Owner\'s Manual',
      types: ['Class C Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2017%20Jayco%20Redhawk%20OM%20Black%20and%20White.pdf',
      cover: '../assets/manuals/library/2017-jayco-redhawk-om-black-and-white-1-02478.webp', coverW: 300, coverH: 392 },
    { name: 'Seismic Manual', years: [2017], kind: 'Owner\'s Manual',
      types: ['Toy Haulers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2017%20Jayco%20Seismic%20OM_Black%20and%20White.pdf',
      cover: '../assets/manuals/library/2017-jayco-seismic-om-black-and-white-1-02494.webp', coverW: 300, coverH: 392 },
    { name: 'Seneca Manual', years: [2017], kind: 'Owner\'s Manual',
      types: ['Class C Motorhomes'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/2017%20Jayco%20Seneca%20OM%20Black%20and%20White.pdf',
      cover: '../assets/manuals/library/2017-jayco-seneca-om-black-and-white-1-02512.webp', coverW: 300, coverH: 392 },
    { name: 'White Hawk Manual', years: [2017], kind: 'Owner\'s Manual',
      types: ['Travel Trailers'],
      pdf: 'https://www.jayco.com/uploads/rvs/manuals/RevA_2017%20Jayco%20Whitehawk%20OM%20Black%20and%20White.pdf',
      cover: '../assets/manuals/library/2017-jayco-whitehawk-om-black-and-white-1-03434.webp', coverW: 300, coverH: 392 },
  ];
}());
