/* ===================================================
   Jayco — Options and packages: each model's "Standard
   Features and Options" panel on jayco.com
   ---------------------------------------------------
   Harvested 2026-09-24, one floorplan page per model
   (the panel is the same on every plan of a model).
   Rendered as the Options and Packages tabs of the
   "Every number." section (model-detail.js).

   • `packages` — every package Jayco lists, in its
     order. `status` is Jayco's "(Mandatory)" or
     "(Optional)"; absent where Jayco says neither
     (Eagle's 4 Star Handling and Luxury PLUS, Jay
     Feather Air's Baja). `note` is the rest of the
     heading's parenthetical ("Sport Edition").
   • `options` — the "Options" list.

   Every line (option or package item) has Jayco's
   parenthetical read into fields:
   • `only`   — "(21MBH, 23MBD, 25BH)": these plans alone
   • `except` — "(n/a 18RBF, 19MRK)": not these
   • `note`   — anything else ("Select models",
                "Requires 50-amp service"); "IPO" and
                "ILO" are written out as "in place of"
   A floorplan page shows only the lines its plan can
   take; a model page shows them all, with the plans.
   Repeats in Jayco's lists are merged.
   =================================================== */

window.JAYCO_OPTIONS = {
  'alante': {
    packages: [
      { name: "Customer Value Package", status: "Mandatory", items: [
        { title: "JRide®: Computer-balanced driveshaft, Bilstein® steering stabilizer, jounce bumpers, heavy-duty front and rear stabilizer bars, SACHS shocks" },
        { title: "JBL® Exterior speakers, with Smart TV and Bluetooth® receiver" },
        { title: "Electric patio awning with LED lights" },
        { title: "Slideout topper awning(s)" },
        { title: "1,200W inverter" },
        { title: "Sony® infotainment center with Apple CarPlay® and Android Auto™" },
        { title: "Backup and side-view cameras" },
        { title: "Smart TV in living area" },
        { title: "200W solar panel with dual controller" },
        { title: "JBL® Audio system" },
      ] },
    ],
    options: [
      { title: "Drop-down overhead bunk in cab area with 750 lb. capacity" },
      { title: "Theater seating", only: ["29s"] },
      { title: "Smart TV in bedroom" },
      { title: "Fabric Sofa / Theater Option" },
    ],
  },
  'comet': {
    packages: [
      { name: "Customer Value Package", status: "Mandatory", items: [
        { title: "Truma Combi G Comfort Plus" },
        { title: "Passenger swivel seat" },
        { title: "6-way adjustment driver and passenger seats" },
        { title: "2,000W inverter" },
        { title: "Cockpit and Privacy Shades" },
        { title: "Driver/Passenger Entry Steps" },
      ] },
    ],
    options: [
      { title: "200W roof-mounted solar panel", only: ["18c"] },
      { title: "Aluminum rims" },
      { title: "Electric patio awning with LED light strip", only: ["18l"] },
      { title: "A/C option", only: ["18l"] },
    ],
  },
  'eagle-fw': {
    packages: [
      { name: "Customer Value Package", status: "Mandatory", items: [
        { title: "15K BTU \"Whisper Quiet\" A/C and bedroom A/C prep" },
        { title: "4K Ultra LED HD Smart TV in living room", note: "Varies from 40\" to 65\"" },
        { title: "50-amp service with fully ducted A/C System" },
        { title: "60K on-demand tankless water heater" },
        { title: "Custom machined aluminum rims" },
        { title: "Electric patio awning" },
        { title: "Hidden hinges soft close cabinet doors" },
        { title: "Interior \"MB Quart Entertainment\" w/ MB Quart Sound", note: "TV & Phone" },
        { title: "Keyed-Alike™ lock system" },
        { title: "Suburban entry steps with blue LED light", note: "Main entrance" },
        { title: "Rain proof bathroom power vent" },
        { title: "Rear 2 in. towing receiver", note: "4-pin connector on fifth wheels only" },
        { title: "Winegard Air 360 Antenna" },
        { title: "Overlander I Solar Package" },
        { title: "Inverter pre-wire", note: "Multiple locations throughout" },
      ] },
      { name: "4 Star Handling Package", items: [
        { title: "Dexter® Axles with NEV-R-Adjust® brakes and E-Z Lube® hubs" },
        { title: "15\" Rainier \"E\" Rated tires OR 16\" Rainier \"H\" Rated tires" },
        { title: "MORryde® CRE-3000™ rubberized suspension" },
        { title: "Wet bolt fasteners with bronze bushings" },
      ] },
      { name: "Luxury PLUS Package", items: [
        { title: "Blackout roller shades with reflective side throughout" },
        { title: "Electric auto-leveling" },
        { title: "Complete NUVOH20 water softening & filtration system" },
        { title: "JayPort™ 2 in. mount", note: "For outside accessories" },
        { title: "Residential style glass shower door" },
        { title: "Washer/dryer prep", note: "Select models" },
        { title: "30 in. over-the-range microwave with exhaust fan" },
        { title: "21 in. oven w/ 3 burner stove top" },
        { title: "Dove Tail Drawers throughout" },
        { title: "Solid Surface Kitchen Countertop(s)" },
        { title: "LED fireplace with 5,000 BTU electric space heater", note: "Select models" },
        { title: "Exterior Light & Outlet at the JayPort Location" },
        { title: "Soft closed cabinet doors throughout", note: "Upper & lower" },
        { title: "Copper Infused 8\" thick mattress w/ temperature regulating material" },
        { title: "Custom Padded Headboard w/ Cell Phone & Tablet holder", note: "Bed slides only" },
        { title: "Residential 66 in. x 80 in. Olympic Mattress w/ under-bed storage" },
        { title: "\"Camp Mode\" & \"Storage Mode\" Power Disconnect" },
        { title: "Black glass, 12V refrigerator" },
      ] },
    ],
    options: [
      { title: "Overlander II Solar Package" },
      { title: "Extreme Weather Package" },
      { title: "Ducted 2nd 15K A/C" },
      { title: "Ducted 3rd 15K A/C", note: "On select models" },
      { title: "Dual Pane Frameless Tinted Safety Glass Windows" },
      { title: "HALO Outside Griddle with Deep Sink for JayPort System" },
      { title: "Dexter ABS Brake System w/Anti-Sway" },
      { title: "SpartanLync TPMS Monitoring" },
      { title: "2nd Power Awning with LED Lights", note: "Select models" },
      { title: "Furniture Cup Holder Tables", note: "1 pair" },
      { title: "King Bed 72\" X 80\" Copper Cool Mattress" },
    ],
  },
  'eagle-sle-fw': {
    packages: [
      { name: "Customer Value Package", status: "Mandatory", items: [
        { title: "15K BTU \"Whisper Quiet\" A/C and bedroom A/C prep" },
        { title: "4K Ultra LED HD Smart TV in living room", note: "Varies from 40\" to 50\"" },
        { title: "50-amp service with fully ducted A/C System" },
        { title: "60K on-demand tankless water heater" },
        { title: "Custom machined aluminum rims" },
        { title: "Electric patio awning" },
        { title: "Hidden hinges soft close cabinet doors" },
        { title: "Interior \"MB Quart Entertainment\" w/ MB Quart Sound", note: "TV & Phone" },
        { title: "Keyed-Alike™ lock system" },
        { title: "Suburban entry steps with blue LED light", note: "Main entrance" },
        { title: "Rain proof bathroom power vent" },
        { title: "Rear 2 in. towing receiver", note: "4-pin connector on fifth wheels only" },
        { title: "Winegard Air 360 Antenna" },
        { title: "Overlander I Solar Package" },
        { title: "Inverter pre-wire", note: "Multiple locations throughout" },
      ] },
      { name: "4 Star Handling Package", items: [
        { title: "Dexter® Axles with NEV-R-Adjust® brakes and E-Z Lube® hubs" },
        { title: "15\" Rainier \"E\" Rated tires" },
        { title: "MORryde® CRE-3000™ rubberized suspension" },
        { title: "Wet bolt fasteners with bronze bushings" },
      ] },
      { name: "Luxury Package", items: [
        { title: "Residential stringless night shades throughout" },
        { title: "Retractable Shower curtain w/ mold resistant material" },
        { title: "Dove Tail Drawers throughout" },
        { title: "Soft closed cabinet doors throughout", note: "Upper & lower" },
        { title: "NUVO H20 + filtration & softening system" },
        { title: "LED fireplace w/ 5,000 BTU electric space heater", note: "Select models" },
        { title: "\"Camp Mode\" & \"Storage Mode\" Power Disconnect" },
        { title: "Electric rear stabilizer jacks" },
        { title: "Copper Infused mattress with temperature regulating material" },
      ] },
    ],
    options: [
      { title: "Overlander II Solar Package" },
      { title: "Ducted 2nd 15K BTU A/C in Bedroom" },
      { title: "2nd Power Awning w/ LED Lights", note: "Select models" },
      { title: "Free-Standing Table & Chairs w/ Bench Seat in place of Dinette Booth", only: ["28bhu", "28rks", "30rlt"] },
      { title: "2 foldable Dinette Chairs" },
      { title: "Furniture Cup Holder Tables", note: "1 pair" },
      { title: "Theater Seating Sofa ipo Tri-Fold Sofa", only: ["24mle", "28bhu", "28rks", "34mbl"] },
    ],
  },
  'eagle-tt': {
    packages: [
      { name: "Customer Value Package", status: "Mandatory", items: [
        { title: "15K BTU \"Whisper Quiet\" A/C and bedroom A/C prep" },
        { title: "4K Ultra LED HD Smart TV in living room", note: "Varies from 40\" to 50\"" },
        { title: "50-amp service with fully ducted A/C System" },
        { title: "60K on-demand tankless water heater" },
        { title: "Custom machined aluminum rims" },
        { title: "Electric patio awning" },
        { title: "Hidden hinges soft close cabinet doors" },
        { title: "Interior \"MB Quart Entertainment\" w/ MB Quart Sound", note: "TV & Phone" },
        { title: "Keyed-Alike™ lock system" },
        { title: "Suburban® entry steps with blue LED light", note: "Main entrance" },
        { title: "Rain proof bathroom power vent" },
        { title: "Rear 2 in. towing receiver" },
        { title: "Winegard Air 360 Antenna" },
        { title: "Overlander I Solar Package", note: "200W panel and 30-amp solar controller" },
        { title: "Inverter pre-wire", note: "Multiple locations throughout" },
      ] },
      { name: "Luxury Package", status: "Mandatory", items: [
        { title: "Residential stringless night shades throughout" },
        { title: "Retractable Shower curtain w/ mold resistant material" },
        { title: "Dove Tail Drawers throughout" },
        { title: "Soft closed cabinet doors throughout", note: "Upper & lower" },
        { title: "NuvoH2O+ citrus-based water filtration & softening treatment system", note: "Extends the life of your water heater, plumbing fixtures, and appliances" },
        { title: "LED fireplace with 5,000 BTU electric space heater", note: "Select models" },
        { title: "\"Camp Mode\" & \"Storage Mode\" Power Disconnect" },
        { title: "Washer/Dryer Prep", note: "Select models" },
        { title: "Solid Surface Kitchen Countertop(s)" },
        { title: "Copper-infused 8 in. thick mattress with temperature regulating material" },
        { title: "Custom Padded Headboard with Cellphone & Tablet holder", note: "Bed slides only" },
        { title: "Residential 66 in. x 80 in. Olympic Mattress with under-bed storage" },
      ] },
      { name: "4 Star Handling Package", status: "Mandatory", items: [
        { title: "Dexter Axles with NEV-R-Adjust® brakes and E-Z Lube® hubs" },
        { title: "15 in. Rainier E-Rated tires OR 16 in. Rainier H-Rated tires" },
        { title: "MORryde CRE-3000™ rubberized suspension" },
        { title: "Wet bolt fasteners with bronze bushings" },
      ] },
    ],
    options: [
      { title: "Overlander II Solar Package", note: "400W Solar & 30-amp controller" },
      { title: "Extreme Weather Package" },
      { title: "Appliance & Electronics" },
      { title: "Bedroom A/C Prep" },
      { title: "Ducted 2nd 15K A/C" },
      { title: "Ducted 3rd 15K A/C" },
      { title: "Stabilizer Jacks with power prep", note: "2 sets" },
      { title: "Electric Auto Leveling System" },
      { title: "22 in. Outside Griddle with Deep Sink for JayPort™ System" },
      { title: "Standard Brakes" },
      { title: "15 in. Tire & Dexter ABS Brake with Anti-Sway" },
      { title: "15 in. Tire with TPMS & Dexter ABS Brake with Anti-Sway" },
      { title: "16 in. H-rated Tires", note: "Forced on select models" },
      { title: "16 in. H-rated Tires with TPMS" },
      { title: "16 in. Tire & Dexter ABS Brake with Anti-Sway" },
      { title: "16 in. Tire with TPMS & Dexter ABS Brake with Anti-Sway" },
      { title: "Winter Shipping Shield" },
      { title: "2nd Power Awning with LED Lights", note: "Select models" },
      { title: "King Bed 72 in. x 80 in." },
    ],
  },
  'greyhawk': {
    packages: [
      { name: "Customer Value Package", status: "Mandatory", items: [
        { title: "JRide® Plus: Computer-balanced driveshaft, Koni® FSD shocks, heavy-duty rear stabilizer bar, standard front stabilizer bar, Hellwig® helper springs, rubber isolation mounts" },
        { title: "Automatic hydraulic leveling jacks" },
        { title: "Frameless windows" },
        { title: "Electric patio awning with LED lights" },
        { title: "15,000 BTU A/C with heat pump" },
        { title: "1,000W inverter" },
        { title: "Sony® infotainment center with tilt/swivel, Apple® CarPlay and Android Auto™" },
        { title: "Backup and side-view cameras" },
        { title: "LED HD Smart TV in living area" },
      ] },
    ],
    options: [
      { title: "Power theater seating" },
      { title: "LED HD Smart TV in bedroom" },
      { title: "Dual 13,500 BTU A/C units with power management system - no heat pump" },
      { title: "Aluminum rims" },
      { title: "Folding windshield sun shade" },
    ],
  },
  'greyhawk-xl': {
    packages: [
      { name: "Customer Value Package", status: "Mandatory", items: [
        { title: "JRide® Plus: Computer-balanced driveshaft, heavy-duty rear stabilizer bar and standard front stabilizer bar" },
        { title: "Hydraulic leveling jacks" },
        { title: "2,000W inverter" },
        { title: "15,000 BTU A/C with heat pump" },
        { title: "200W solar panel with dual controller and second house battery" },
        { title: "Smart TV in living area" },
        { title: "JBL® audio system" },
        { title: "JBL® Exterior speakers, with Smart TV and Bluetooth® receiver" },
        { title: "Slideout topper awning(s)" },
        { title: "Solid-surface kitchen countertops" },
      ] },
    ],
    options: [
      { title: "Power theater seating" },
      { title: "Smart TV in bedroom", only: ["32u", "33f"] },
      { title: "Dual A/C units with power management system - no heat pump", note: "15,000 and 13,500 BTU" },
      { title: "Aluminum rims" },
      { title: "Folding windshield sun shade" },
      { title: "All terrain tires- 245/70R19.5" },
      { title: "Chassis upgrade- 4600", only: ["32u"] },
      { title: "Golden State Edition Package Golden State Edition Package Golden State Full-Body Paint", note: "F550 Chassis - Only availably on 32U in California. All floor plans - Non CA Dealers" },
      { title: "Heavy-duty front stabilizer bar" },
      { title: "Upgraded Koni FSD shocks" },
      { title: "2 in. BDS radius arm suspension lift" },
      { title: "Aluminum wheels" },
      { title: "Upgraded front bumper" },
      { title: "Aftermarket grille" },
      { title: "Desert Edition", note: "All Floorplans - Non CA Dealers" },
    ],
  },
  'jay-feather': {
    packages: [
      { name: "Customer Value Package", status: "Mandatory", items: [
        { title: "13,500 BTU ducted roof-mount Quiet Series A/C" },
        { title: "20 lb. LP gas bottles with auto regulator, ABS cover and fill gauge" },
        { title: "4 - Stabilizer jacks" },
        { title: "55 gal. fresh water tank" },
        { title: "Automotive-style aluminum rims" },
        { title: "Barreled ceiling", 'except': ["18rbf", "19mrk", "21mml", "21mbh", "23rk", "25bh"] },
        { title: "Black tank flush" },
        { title: "Detachable power cord" },
        { title: "Electric fireplace", 'except': ["211mml", "21mbh", "23rk", "23mbd", "25bh"] },
        { title: "Hidden cabinet hinges" },
        { title: "Max-length power awning with LED lights" },
        { title: "NuvoH2O plus water filtration and softening prepped system" },
        { title: "On-demand 60,000 BTU tankless water heater" },
        { title: "Power tongue jack" },
        { title: "Radial tires with self-adjusting electric brakes" },
        { title: "Rear back-up camera prep" },
        { title: "Residential cabinetry with large doors and drawers" },
        { title: "Roller shades with radiant barrier backer" },
        { title: "Slide topper prep" },
        { title: "Under-mount spare tire" },
        { title: "Vacuum-bonded sidewalls with interior and exterior Azdel®" },
      ] },
      { name: "Jay Sport Package", status: "Mandatory", items: [
        { title: "11 cu. ft. 12V refrigerator" },
        { title: "2 in. rear receiver hitch" },
        { title: "Bathroom and living room 12V vent fans" },
        { title: "Climate Shield™", note: "Zero to 100 degree tested weather insulation package" },
        { title: "Dark-tinted privacy windows" },
        { title: "Front exterior accent fusion light" },
        { title: "Front molded cap", 'except': ["18rbf", "19mrk", "21mml", "21mbh", "23rk", "25bh"] },
        { title: "Front slam-latch baggage doors" },
        { title: "Inverter pre-wire outlets" },
        { title: "InVision™ kitchen appliance package" },
        { title: "Keyed-Alike™ lock system" },
        { title: "LED smart TV" },
        { title: "Modern graphics package" },
        { title: "Outside TV prep" },
        { title: "Overlander I Solar Package: 1 - 200W solar panel and 30-amp digital controller" },
        { title: "Porcelain foot-flush toilet with soft close lid" },
        { title: "Rear exterior ladder" },
        { title: "Solid fold-down step(s)" },
        { title: "Stainless steel single basin kitchen sink" },
      ] },
      { name: "Premier Package", status: "Optional", items: [
        { title: "Dual MaxxAir® vent fan in bathroom and living room" },
        { title: "Multi-function \"All in One\" stainless steel kitchen sink" },
        { title: "Power 5-point stabilization system" },
        { title: "Premier graphic legend" },
        { title: "Solid surface kitchen countertops" },
      ] },
    ],
    options: [
      { title: "120V heated tank pads" },
      { title: "15,000 BTU ducted Quiet Series A/C", note: "In place of 13,500 BTU A/C" },
      { title: "2nd 13,500 BTU ducted Quiet Series A/C", note: "Requires 50-amp service" },
      { title: "30 lb. LP gas bottles with auto regulator, ABS cover, and fill gauge" },
      { title: "50-amp service with 2nd and 3rd A/C prep", 'except': ["18rbf", "19mrk", "21mml", "21mbh"] },
      { title: "72 in. x 80 in. king bed", note: "Select models" },
      { title: "App monitoring in-stem TPMS" },
      { title: "Freestanding table and 4 chairs", note: "Select models" },
      { title: "Furniture cup holder tables", note: "1 pair" },
      { title: "Overlander II Solar Package: 2 - 200W panels, MPPT 30-amp solar controller and 1800W inverter" },
      { title: "Theater seating in place of tri-fold sofa", only: ["25rb", "27bh", "27mk", "29bhb", "29qbh", "30rkb", "33bh"] },
      { title: "Theater seating with trays in place of dinette", only: ["21mbh", "23mbd", "25bh"] },
      { title: "Theater seating with trays in place of tri-fold sofa", only: ["18rbf"] },
    ],
  },
  'jay-feather-air': {
    packages: [
      { name: "Customer Value Package", status: "Mandatory", items: [
        { title: "13,500 BTU roof-mounted Quiet Series A/C" },
        { title: "20 lb. LP gas bottle with auto regulator, ABS cover and fill gauge" },
        { title: "2 - burner cooktop with glass stove-top cover" },
        { title: "4 - scissor stabilizer jacks", note: "Not available with baja package" },
        { title: "55 gal. freshwater tank" },
        { title: "Air fryer convection microwave" },
        { title: "Automotive-style aluminum rims" },
        { title: "Black tank flush" },
        { title: "Detachable power cord" },
        { title: "Hidden cabinet hinges" },
        { title: "Max-length power awning with LED light" },
        { title: "On-demand 60,000 BTU water heater" },
        { title: "Power tongue jack" },
        { title: "Radial tires with self-adjusting electric brakes" },
        { title: "Rear back-up camera prep" },
        { title: "Residential cabinetry with large doors and drawers" },
        { title: "Roller shades with radiant barrier backer" },
        { title: "Soft close toilet lid" },
        { title: "Under-mount spare tire" },
        { title: "Vacuum-bonded sidewalls with interior and exterior Azdel®" },
      ] },
      { name: "Jay Air Package", status: "Mandatory", items: [
        { title: "11 cu. ft. 12V refrigerator" },
        { title: "2 in. rear receiver prepped" },
        { title: "Black stainless steel single-basin kitchen sink" },
        { title: "Climate Shield™ zero to 100 degree tested weather insulation package" },
        { title: "Dark-tinted privacy windows" },
        { title: "Inverter pre-wired outlets" },
        { title: "Invision™ kitchen appliance package" },
        { title: "Keyed-Alike™ lock system" },
        { title: "LED smart TV" },
        { title: "Modern graphics package" },
        { title: "Outside TV prepped" },
        { title: "Overlander I Solar Package: 200W solar panel and 30-amp digital controller" },
        { title: "Rear exterior ladder" },
        { title: "Solid fold-down exterior step" },
      ] },
      { name: "Baja Package", items: [
        { title: "2 in. rear receiver hitch" },
        { title: "Anchor drop stabilizer system" },
        { title: "Baja graphics" },
        { title: "Off-road tires with app monitoring in-stem TPMS" },
        { title: "Rear diamond plating" },
        { title: "Torsion axle" },
      ] },
    ],
    options: [
      { title: "2 - 30 lb. LP gas bottles with auto regulator, ABS cover and fill gauge" },
      { title: "120V heated tank pads" },
      { title: "15,000 BTU Mach Quiet Series A/C" },
      { title: "2 in. rear receiver hitch", note: "Included in Baja package" },
      { title: "App monitoring in-stem TPMS", note: "Included in Baja package" },
      { title: "MaxxAir® vent fan" },
      { title: "Overlander II Solar Package: 2 - 200W panels, MPPT 30-amp solar controller and 1800W inverter" },
    ],
  },
  'jay-feather-air-sl': {
    packages: [
      { name: "Customer Value Package", status: "Mandatory", items: [
        { title: "13,500 BTU roof mount A/C" },
        { title: "19,000 BTU furnace" },
        { title: "2 - burner stove top" },
        { title: "20 lb. LP bottle with auto regulator and fill gauge" },
        { title: "5 cu. ft. 12V refrigerator" },
        { title: "Dark-tinted privacy windows" },
        { title: "Detachable power cord" },
        { title: "Electric vent in bathroom and kitchen" },
        { title: "Entry door with window and shade prep" },
        { title: "Exterior security light" },
        { title: "Front tongue jack" },
        { title: "Hidden cabinet hinges" },
        { title: "Inverter pre-wire outlets" },
        { title: "Keyed-Alike™ lock system" },
        { title: "LED interior and exterior lights" },
        { title: "Microwave oven" },
        { title: "On-demand tankless water heater" },
        { title: "Pleated window shades" },
        { title: "Plywood dinette bases" },
        { title: "Power awning" },
        { title: "Radial tires with self-adjusting electric brakes" },
        { title: "Rear back-up camera prep" },
        { title: "Rear bumper" },
        { title: "Roof mount solar prep" },
        { title: "Shower surround" },
        { title: "Soft close toilet lid" },
        { title: "Stabilizer jacks" },
        { title: "Vacuum-bonded sidewalls with interior and exterior Azdel®" },
      ] },
    ],
    options: [
      { title: "Overlander I Solar Package: 1 200W solar panel and 30-amp digital controller" },
      { title: "L-dinette", only: ["17rbsl"] },
    ],
  },
  'jay-feather-sl': {
    packages: [
      { name: "Customer Value Package", status: "Mandatory", items: [
        { title: "11 cu. ft. 12V refrigerator" },
        { title: "13,500 BTU ducted roof A/C" },
        { title: "2 in. receiver hitch prep" },
        { title: "20 lb. LP bottle with auto regulator and fill gauge" },
        { title: "55 gal. fresh water tank" },
        { title: "4 - Stabilizer jacks" },
        { title: "Automotive-style aluminum rims" },
        { title: "Bathroom skylight" },
        { title: "Detachable power cord" },
        { title: "Electric fireplace prep" },
        { title: "Electric vent in bathroom" },
        { title: "Entry door with window and shade prep" },
        { title: "G20 dark-tinted privacy windows" },
        { title: "Hidden cabinet hinges" },
        { title: "Inverter pre-wire outlets" },
        { title: "Invision™ kitchen appliance package" },
        { title: "Keyed-Alike™ lock system" },
        { title: "Large folding entry door grab handle" },
        { title: "LED interior and exterior lights" },
        { title: "On-demand tankless water heater" },
        { title: "Outside TV prep" },
        { title: "Pleated window shades" },
        { title: "Power awning with LED lights" },
        { title: "Power tongue jack" },
        { title: "Radial tires with self-adjusting electric brakes" },
        { title: "Rear back-up camera prep" },
        { title: "Residential cabinetry with large doors and drawers" },
        { title: "Roof mount solar prep" },
        { title: "Shower surround" },
        { title: "Soft close toilet lid" },
        { title: "Solid fold-down exterior step" },
        { title: "Under-mount spare tire" },
        { title: "Vacuum-bonded sidewalls with interior and exterior Azdel®" },
      ] },
    ],
    options: [
      { title: "15,000 BTU ducted roof mount A/C" },
      { title: "2nd 13,500 BTU ducted roof mount A/C - requires 50-amp service" },
      { title: "50-amp service" },
      { title: "Overlander I Solar package: 1- 200W solar panel and 30-amp digital controller" },
      { title: "Theater seating", note: "In place of jack-knife sofa" },
      { title: "Tri-fold sofa", note: "In place of jack-knife sofa" },
    ],
  },
  'jay-flight': {
    packages: [
      { name: "Customer Value Package", status: "Mandatory", items: [
        { title: "8 cu. ft. 12V refrigerator", note: "Single axle" },
        { title: "11 cu. ft. 12V refrigerator", note: "Double axles" },
        { title: "AM/FM/Bluetooth® stereo", note: "Not on single axles" },
        { title: "Backup camera prep" },
        { title: "Bathroom skylight" },
        { title: "Bathroom vent" },
        { title: "Detachable power cord" },
        { title: "Entry door with window and shade prep" },
        { title: "Fitted bed sheet" },
        { title: "G20 dark-tinted privacy windows" },
        { title: "Keyed-Alike™ entry and baggage doors" },
        { title: "Large folding entry door grab handle" },
        { title: "LED interior and exterior lights" },
        { title: "Microwave oven" },
        { title: "MORryde StepAbove® entry steps" },
        { title: "On-demand tankless water heater" },
        { title: "Power awning with LED lights" },
        { title: "2-burner cooktop", note: "Single axles" },
        { title: "17-inch gas range with 3-burner cooktop", note: "Double axles" },
        { title: "Range hood" },
        { title: "Residential refrigerator", only: ["380dqs", "382frk"] },
        { title: "Spare tire with cover" },
        { title: "Stabilizer jacks" },
        { title: "Tub/shower surround" },
        { title: "Window shades" },
      ] },
      { name: "Customer Value Package", status: "Mandatory", note: "Sport Edition", items: [
        { title: "12V refrigerator" },
        { title: "19,000 BTU furnace" },
        { title: "20 lb. LP bottle" },
        { title: "2-burner stovetop" },
        { title: "Bathroom vent" },
        { title: "Detachable power cord" },
        { title: "Entry door with window and shade prep" },
        { title: "Front tongue jack" },
        { title: "G20 dark-tinted privacy windows" },
        { title: "LED interior and exterior lights" },
        { title: "Microwave oven" },
        { title: "On-demand tankless water heater" },
        { title: "Power awning" },
        { title: "Rear bumper" },
        { title: "Stabilizer jacks" },
        { title: "Window shades" },
      ] },
      { name: "25th Anniversary Package", status: "Mandatory", note: "Single Axle", items: [
        { title: "Anniversary exterior entrance mat" },
        { title: "Armor-coat exterior metal" },
        { title: "New enhanced exterior graphics" },
        { title: "New professionally designed interior" },
      ] },
      { name: "25th Anniversary Package", status: "Mandatory", note: "Double Axles. Not on Sport Edition", items: [
        { title: "11 cu. ft. 12V refrigerator" },
        { title: "Enhanced exterior graphics package" },
        { title: "New exterior wall metal design", note: ".030 thickness" },
        { title: "Slideout endwall windows", note: "Where applicable" },
        { title: "Smart bedroom design: under-bed cubbies and wardrobe cubbies with USB and USB-C's" },
        { title: "Smooth exterior front metal wall", note: ".040 thickness" },
      ] },
      { name: "Elite Package", status: "Optional", note: "On slideout models", items: [
        { title: "Aluminum rims" },
        { title: "Decorative window surrounds in living area" },
        { title: "Dinette storage doors" },
        { title: "Enhanced graphics" },
        { title: "Fiberglass sidewalls" },
        { title: "Fireplace", 'except': ["225mls"] },
        { title: "Front accent LED lighting" },
        { title: "Pull-out kitchen faucet" },
        { title: "Window in slideout end wall" },
      ] },
      { name: "Baja Package", status: "Optional", note: "Western-built units only – select single axles", items: [
        { title: "30 lb. LP bottle" },
        { title: "4 - Stabilizer jacks" },
        { title: "Aluminum rims" },
        { title: "Deluxe graphic package" },
        { title: "Enclosed underbelly" },
        { title: "Off-road tires" },
        { title: "Oversized wheel fenders" },
        { title: "Triple entry step" },
      ] },
      { name: "Baja Package", status: "Optional", note: "Western-built units only – select double axles", items: [
        { title: "2 - 30 lb. LP bottles" },
        { title: "Increased ground clearance" },
        { title: "Off-road tires" },
        { title: "Oversized wheel fenders" },
        { title: "Triple Tread step" },
      ] },
    ],
    options: [
      { title: "13,500 BTU roof-mount A/C" },
      { title: "Aluminum rims", note: "Standard on with Elite pkg." },
      { title: "Fiberglass sidewalls", note: "Select models" },
      { title: "Outside griddle with LP quick-connect hose" },
      { title: "Overlander I Solar Package: 1- 200W solar panel and 30-amp digital controller" },
      { title: "15,000 BTU roof-mounted A/C" },
      { title: "2nd 13,500 BTU roof-mounted A/C", note: "Select models" },
      { title: "3rd 13,500 BTU roof-mounted A/C", note: "Select models" },
      { title: "50 amp service", note: "Standard on 325BHT, 334RTS, 380DQS, 382FRK" },
      { title: "Baja package", note: "Western-built units only - select models" },
      { title: "Bumper mount outside griddle with LP quick connect hose and mounting hardware" },
      { title: "72 in. x 80 in. king bed", note: "Select models" },
      { title: "LED smart TV" },
      { title: "Overlander 1 Solar package: 1-200W solar panel and 30-amp digital controller" },
      { title: "Outside griddle", 'except': ["265th"] },
      { title: "Table and chairs" },
      { title: "Theater seating sofa" },
      { title: "Tri-fold sofa" },
    ],
  },
  'jay-flight-bungalow': {
    packages: [
      { name: "Customer Value Package", status: "Mandatory", items: [
        { title: "15,000 BTU A/C" },
        { title: "15,000 BTU 2nd A/C" },
        { title: "2 - 30 lb. LP propane bottles with cover" },
        { title: "AM/FM/Bluetooth® stereo interior and exterior speakers" },
        { title: "Bathroom skylight" },
        { title: "Ceiling fan" },
        { title: "Detachable power cord" },
        { title: "G20 dark-tinted privacy windows" },
        { title: "LED interior and exterior lights" },
        { title: "One-piece front fiberglass wall" },
        { title: "Oversized side windows" },
        { title: "Power awning with LED light" },
        { title: "Power vent in bathroom" },
        { title: "Privacy window shades throughout" },
        { title: "Shower/tub surround" },
        { title: "Sink cover/ cutting board" },
        { title: "Thermal Package: insulated and enclosed underbelly" },
      ] },
      { name: "25th Anniversary Package", status: "Mandatory", items: [
        { title: "Anniversary exterior entrance mat" },
        { title: "Armor-coat exterior metal" },
        { title: "New enhanced exterior graphics" },
        { title: "New professionally designed interior" },
      ] },
    ],
    options: [
      { title: "3rd A/C" },
      { title: "73 in. x 80 in. king bed" },
      { title: "Fiberglass slidewalls" },
      { title: "Residential plumbing package" },
    ],
  },
  'north-point': {
    packages: [
      { name: "Customer Value Package", status: "Mandatory", items: [
        { title: "15K BTU “Whisper Quiet” A/C / 15K BTU “Whisper Quiet” A/C", note: "Main. Bedroom" },
        { title: "On-demand tankless hot water heater" },
        { title: "4K Smart LED HDTV with fully digital HDMI® output and two extra HDMI cables" },
        { title: "Backup, main entrance door, and side observation security camera prep", note: "Includes a power switch in the bedroom to use the monitor for security" },
        { title: "Custom, black, machined aluminum rims" },
        { title: "Electric patio awning" },
        { title: "Hidden hinges, magnet latches" },
        { title: "JBL® home entertainment system with sound bar and wireless subwoofer" },
        { title: "Keyed-Alike™ lock system", note: "Single key for all doors/locks" },
        { title: "Residential king mattress with under-bed storage", note: "72 x 80 in." },
        { title: "Residential dovetail-jointed drawers throughout" },
        { title: "2 30 lb. propane bottles with auto regulator" },
        { title: "Overlander I Solar Package" },
      ] },
      { name: "Customer Value Package", status: "Optional", items: [
        { title: "With 15,000 BTU A/C and Heat Pump" },
      ] },
      { name: "5 Star Handling Package", status: "Mandatory", items: [
        { title: "Dexter® axles with Nev-R-Adjust® brakes and E-Z Lube® hubs" },
        { title: "MORryde® CRE3000™ rubberized suspension system" },
        { title: "Rota-flex® pin box" },
        { title: "Wet-bolt fasteners with bronze bushings" },
        { title: "4,000 lb. leaf springs" },
        { title: "17.5 in. 16-ply tires" },
      ] },
      { name: "Luxury Package", status: "Mandatory", items: [
        { title: "2nd electric patio awning" },
        { title: "6-point hydraulic auto-leveling system" },
        { title: "Frameless dark-tinted safety-glass windows" },
        { title: "Free-standing roll-top table with two freestanding chairs and two folding chairs", note: "No pedestal" },
        { title: "12V refrigerator with 1,800W inverter" },
        { title: "30 in. space-saving microwave" },
        { title: "21 in. range" },
        { title: "High-gloss gel-coated sidewalls" },
        { title: "LED fireplace with electric space heater" },
        { title: "MORryde® StepAbove™ entrance steps", note: "Main entrance" },
        { title: "Oversized multi-battery compartment" },
        { title: "Privacy night roller shades in living room" },
        { title: "Residential solid-surface kitchen countertops" },
        { title: "Residential walk-in shower with seat prep" },
        { title: "Washer/dryer prep" },
        { title: "Residential NuvoH2O® whole-coach water system with water softening and three replacement cartridges" },
        { title: "Residential “Do-It-All” kitchen sink" },
      ] },
      { name: "Extreme Weather Package", status: "Optional", items: [
        { title: "120V heat pads for holding and freshwater tanks" },
        { title: "12V electric water line wrap" },
        { title: "Interior illuminated switch" },
      ] },
    ],
    options: [
      { title: "3rd living area A/C", note: "15,000 BTU" },
      { title: "Overlander II Solar Package" },
      { title: "Generator prep" },
      { title: "7,000W Onan® dual-fuel generator", note: "Includes generator prep" },
      { title: "Dual-pane tinted safety-glass windows" },
      { title: "3 slideout awnings", only: ["310rlts", "375tbdb", "391tbbh", "365rkts"] },
      { title: "4 slideout awnings", only: ["381ckre", "361rlbh", "395dsdb"] },
      { title: "Outside HALO® griddle for JayPort® system", 'except': ["375tbdb", "391tbbh"] },
      { title: "Theater seating with roll-top dinette", only: ["375tbdb"] },
      { title: "Queen residential foam-top mattress" },
    ],
  },
  'pinnacle': {
    packages: [
      { name: "Customer Value Package", status: "Mandatory", items: [
        { title: "15,000 BTU “Whisper Quiet” bedroom A/C" },
        { title: "15,000 BTU “Whisper Quiet” main A/C with heat pump" },
        { title: "On-demand tankless water heater" },
        { title: "4K Smart LED HDTV with fully digital HDMI® output and two additional HDMI® cables" },
        { title: "Backup, main entry door, and side-view observation camera prep, including bedroom power switch for optional security monitor" },
        { title: "Electric patio awning" },
        { title: "Hidden hinges, magnetic latches, and soft-close cabinet doors" },
        { title: "JBL® home entertainment system with soundbar and wireless subwoofer" },
        { title: "Keyed-Alike™ lock system", note: "Single key for all doors and locks" },
        { title: "MORryde® Safe-T-Rail® grab handle" },
        { title: "Residential king mattress with under-bed storage", note: "72 in. x 80 in." },
        { title: "3 40 lb. LP propane bottles with automatic regulator", note: "120 LP capacity" },
        { title: "Overlander II Solar Package featuring 30-amp controller, 1,800W inverter, and two 200W solar panels" },
      ] },
      { name: "Luxury Package", status: "Mandatory", items: [
        { title: "2nd electric patio awning" },
        { title: "40 in. 4K exterior Smart LED TV" },
        { title: "40 in. 4K Smart LED TV in bedroom" },
        { title: "6-point hydraulic auto-leveling system" },
        { title: "Central vacuum system with dust port" },
        { title: "Day/night roller shades in living room" },
        { title: "Frameless dark-tinted safety-glass windows" },
        { title: "GE® 21 cu.ft. residential refrigerator with 1,800W inverter" },
        { title: "GE Profile™ Series 30 in. residential convection microwave with built-in air fryer" },
        { title: "GE Profile™ Series 24 in. residential range with 3.7 cu.ft. oven and 9,100 BTU high-output burner" },
        { title: "High-gloss gel-coated sidewalls" },
        { title: "LED fireplace with electric space heater" },
        { title: "MORryde® StepAbove™ Stow & Go steps" },
        { title: "Oversized multi-battery compartment with room for 4–6 batteries" },
        { title: "Powered 50-amp cord reel" },
        { title: "Residential solid-surface kitchen and bathroom countertops" },
        { title: "Residential walk-in shower with teak seat" },
        { title: "Solid hardwood cabinet doors, stiles, and fascia with hand-painted 90° poly sheen finish" },
        { title: "Residential “Do-It-All” sink" },
        { title: "Washer/dryer prep" },
        { title: "Pull-out “Roll Top” dinette with two freestanding chairs and two folding chairs" },
        { title: "Residential NuvoH2O® whole-coach water treatment system with water softening and triple-cartridge filtration" },
        { title: "NuvoH2O® Ultra Filter with medical- and military-grade filtration technology for kitchen faucet and refrigerator ice/water dispenser, conveniently located under sink" },
      ] },
      { name: "5 Star Handling Package", status: "Mandatory", items: [
        { title: "17.5 in. 16-ply tires" },
        { title: "Dexter® axles with ABS and Tow Assist, including Nev-R-Adjust® brakes and E-Z Lube® hubs" },
        { title: "MORryde® LRE4000™ rubberized suspension system" },
        { title: "MORryde® rubber pin box" },
        { title: "Wet-bolt fasteners with bronze bushings and 4,000 lb. leaf springs" },
      ] },
    ],
    options: [
      { title: "3rd living area A/C", note: "15,000 BTU" },
      { title: "20 cu. ft. 12V refrigerator" },
      { title: "Generator prep" },
      { title: "7,000W Onan® dual-fuel generator", note: "Includes generator prep" },
      { title: "Dual-pane tinted safety-glass windows" },
      { title: "3 slideout awnings", only: ["36fbts", "32rlts", "38fbrk"] },
      { title: "4 slideout awnings", only: ["38ssws", "39flok"] },
      { title: "Outside Halo® griddle for JayPort® system", only: ["36fbts", "32rlts", "38fbrk", "38ssws"] },
      { title: "7K axle with hydraulic disc brakes", note: "No ABS", only: ["32rlts"] },
      { title: "8K axle with hydraulic disc brakes", note: "No ABS" },
      { title: "MORryde® independent suspension with 8K axles and disc brakes", note: "Not available with ABS" },
      { title: "Queen residential foam-top mattress" },
    ],
  },
  'precept': {
    packages: [
      { name: "Customer Value Package", status: "Mandatory", items: [
        { title: "JRide® Plus: Computer-balanced driveshaft, Safe-T-Plus steering stabilizer, Koni® FDS shocks, variable-rate front and rear jounce bumpers, heavy-duty front and rear stabilizer bars, 22.5in Michelin® tires" },
        { title: "15,000 BTU A/C unit with heat pump and second 13,500 BTU A/C unit" },
        { title: "JBL® Exterior speakers, with Smart TV and Bluetooth® receiver" },
        { title: "1,200W inverter" },
        { title: "Tankless water heater" },
        { title: "Sony® infotainment center with Apple CarPlay® and Android Auto™" },
        { title: "Backup and side-view cameras" },
        { title: "Smart TV in living area" },
        { title: "JBL® Audio system" },
        { title: "200W solar panel with dual controller" },
        { title: "Slideout awning(s)" },
      ] },
    ],
    options: [
      { title: "Drop-down overhead bunk in cab area with 750 lb. capacity" },
      { title: "Combination washer/dryer", only: ["34b", "34g", "36a"] },
      { title: "Stackable washer/dryer", only: ["36c"] },
      { title: "Fabric Sofa/Theater Option", note: "Standard on 34G, 36C", only: ["36a"] },
      { title: "12V Refrigerator" },
    ],
  },
  'precept-prestige': {
    packages: [
      { name: "Customer Value Package", status: "Mandatory", items: [
        { title: "JRide® Plus: Computer-balanced driveshaft, Safe-T-Plus steering stabilizer, Koni® FSD shocks, variable-rate front and rear jounce bumpers, heavy-duty front and rear stabilizer bars, 22.5 in. Michelin® tires" },
        { title: "15,000 BTU A/C unit with heat pump and second 13,500 BTU A/C unit" },
        { title: "JBL® Exterior speakers, with Smart TV and Bluetooth® receiver" },
        { title: "2,000W inverter" },
        { title: "Sony® infotainment center with Apple CarPlay® and Android Auto™" },
        { title: "Backup and side-view cameras" },
        { title: "Smart TV in living area" },
        { title: "200W solar panel with dual controller" },
        { title: "Electric fireplace" },
        { title: "JBL® audio system" },
        { title: "Slideout topper awning(s)" },
      ] },
    ],
    options: [
      { title: "Drop-down overhead bunk in cab area with 750 lb. capacity" },
      { title: "Fabric Sofa/Theater Option", only: ["36b", "36h"] },
      { title: "120 in. straight reclining sofa", only: ["36h"] },
      { title: "Combination washer/dryer", only: ["36u", "36b"] },
      { title: "Stackable washer/dryer", only: ["36h"] },
    ],
  },
  'redhawk': {
    packages: [
      { name: "Customer Value Package", status: "Mandatory", items: [
        { title: "JRide®: Computer-balanced driveshaft, standard front and rear stabilizer bars, Hellwig® helper springs, rubber isolation body mounts" },
        { title: "One-piece, seamless, fiberglass front cap" },
        { title: "Automotive-bonded, panoramic window in front cap with power shade" },
        { title: "Heated holding tanks", note: "12V pads" },
        { title: "Electric patio awning with LED lights" },
        { title: "Black holding tank sprayer" },
        { title: "Sony® infotainment center with tilt/swivel, Apple CarPlay® and Android Auto™" },
        { title: "Backup and side-view cameras" },
        { title: "Smart TV in living area" },
      ] },
    ],
    options: [
      { title: "Automatic hydraulic leveling jacks" },
      { title: "Theater seating in place of dinette and additional TV in cab-over", only: ["24b", "26m"] },
      { title: "200W solar panel with dual controller and second house battery" },
      { title: "Dual 13,500 BTU A/C units with power management system" },
      { title: "Folding windshield sun shade" },
    ],
  },
  'redhawk-se': {
    packages: [
      { name: "Customer Value Package", status: "Mandatory", items: [
        { title: "One-piece, seamless, fiberglass front cap" },
        { title: "Electric patio awning" },
        { title: "Black holding tank sprayer" },
        { title: "Backup camera" },
        { title: "LED HD Smart TV" },
        { title: "Tankless Hot Water Heater" },
      ] },
    ],
    options: [
      { title: "Automatic hydraulic leveling jacks" },
      { title: "200W solar panel with dual controller and second house battery" },
    ],
  },
  'seismic-fw': {
    packages: [
      { name: "Customer Value Package", status: "Mandatory", items: [
        { title: "106 gal. freshwater capacity" },
        { title: "Residential NuvoH2O® whole-coach water treatment system with water softening and triple-cartridge filters" },
        { title: "60,000 BTU on-demand tankless water heater" },
        { title: "2 60 lb. LP gas bottles" },
        { title: "12V 17 cu. ft. black glass refrigerator" },
        { title: "30 in. residential microwave" },
        { title: "21 in. 3-burner oven" },
        { title: "3 high-efficiency soft-start A/Cs" },
        { title: "Teak shower seat prep" },
        { title: "MB Quart® Bluetooth® stereo system with 2 interior and 2 exterior speakers" },
        { title: "4K Smart LED HDTV" },
        { title: "Glass shower door" },
        { title: "Roller blackout nightshades" },
        { title: "Soft-close hidden hinges and magnetic door catches on cabinet doors" },
        { title: "Lumber-core-style face frames" },
        { title: "Triple-slide glass shower door" },
        { title: "Bathroom power vent" },
        { title: "MORryde® 4-step strut-assisted fold-away entrance steps", note: "Main entrance" },
        { title: "Universal docking station with outside shower" },
        { title: "Factory-installed collapsible roof ladder" },
        { title: "Main electric awning with app-controlled RGB LED lights" },
        { title: "Second electric awning with app-controlled RGB LED lights" },
        { title: "Fully enclosed, heated underbelly", note: "Ducted" },
        { title: "Overlander II Solar Package: 400W solar panel, MPPT 30-amp solar controller and 1,800W inverter" },
      ] },
      { name: "Ramp and Cargo Equipment", status: "Mandatory", items: [
        { title: "30 gal. fuel tank with locking enclosed pump and timer" },
        { title: "3-season locking garage wall" },
        { title: "5,000 lb. minimum breaking load garage D-rings mounted to the steel frame" },
        { title: "HappiJac® electric-lift queen beds with convertible sofas, folding armrests and cup holders" },
        { title: "Rear loft ladder" },
        { title: "High-intensity LED ramp lights" },
        { title: "Ram air vents with power roof vent" },
        { title: "Lift-assisted, weatherproof, anti-skid ramp door" },
        { title: "Powder-coated aluminum patio kit with gate and steps" },
        { title: "Tuff-Ply® rubberized garage floor liner" },
        { title: "Power ramp patio awning with LED lighting" },
      ] },
      { name: "5 Star Handling Package", status: "Mandatory", items: [
        { title: "17.5 in. H-rated, 16-ply tires" },
        { title: "Aluminum rims" },
        { title: "Dexter® axles with ABS, Tow Assist and sway mitigation" },
        { title: "Nev-R-Adjust® brakes" },
        { title: "Greaseable wet bolt fasteners with bronze bushings and 4,000 lb. leaf springs" },
        { title: "MORryde® CRE3000 suspension system" },
        { title: "Rota-Flex® king pin" },
        { title: "Backup and side camera prep" },
        { title: "Entry door security camera prep" },
      ] },
    ],
    options: [
      { title: "Tinted safety glass windows" },
      { title: "Frameless dual-pane tinted safety glass windows" },
      { title: "Tank heat pads" },
      { title: "Outside griddle for JayPort™ system" },
      { title: "King bed", note: "Select models" },
      { title: "Queen bed", note: "Select models" },
    ],
  },
  'seismic-tt': {
    packages: [
      { name: "Ramp And Cargo Equipment", status: "Mandatory", items: [
        { title: "30 gal. Fuel tank with locking, enclosed pump and timer" },
        { title: "5,000 lbs. Garage D-rings mounted to the steel frame" },
        { title: "HappiJac® Electric-lift queen beds/convertible sofas with folding armrests and cup holders" },
        { title: "LED high-intensity ramp lights" },
        { title: "Ram air vents and power roof vent" },
        { title: "Tuff-ply, rubberized garage floor liner" },
        { title: "Weather resistant rear ramp door and patio with anti-slip, non-skid flooring" },
        { title: "Power ramp patio awning with LED lighting" },
        { title: "Ramp patio steps" },
        { title: "Roll down garage screen", note: "Unless 3 season door is selected" },
      ] },
      { name: "Customer Value Package", status: "Mandatory", items: [
        { title: "60,000 BTU On-demand tankless hot water heater" },
        { title: "106 gallon fresh water capacity" },
        { title: "Glass front 12V refrigerator" },
        { title: "Residential microwave" },
        { title: "5K BTU A/C" },
        { title: "17 in. oven with 3 burners" },
        { title: "4K Smart LED HDTV" },
        { title: "MB Quart Bluetooth® stereo with 4 speakers" },
        { title: "Roller black out night shades" },
        { title: "Soft close hidden hinges and magnet door catches on cabinet doors" },
        { title: "Lumber core style face frames" },
        { title: "Drop-down knife rack" },
        { title: "Integrated cup washer" },
        { title: "Black stainless single bowl kitchen sink" },
        { title: "Bathroom power vent" },
        { title: "Roll-away shower door" },
        { title: "Jay Port® 2 in. mount", note: "For outside accessories" },
        { title: "Power tongue Jack with LED light" },
        { title: "Electric awning with LED lighting" },
        { title: "High gloss gel coat exterior fiberglass side walls" },
        { title: "Fully enclosed and heated underbelly", note: "Ducted" },
        { title: "MORryde® Fold Away Entrance Steps", note: "Main Entrance" },
        { title: "LED fireplace with electric 5,000 BTU space heater", note: "Select models" },
        { title: "Keyed-Alike™ lock system" },
        { title: "Overlander 1 Solar Package", note: "200W panel and 30-amp solar controller" },
      ] },
      { name: "5 Star Handling Package", status: "Mandatory", items: [
        { title: "Dexter® axles with Nev-R-Adjust® brakes and E-Z Lube® hubs" },
        { title: "Wet bolt fasteners, bronze bushings" },
        { title: "4,000 lbs. leaf springs" },
        { title: "CRE 3000 suspension" },
        { title: "16\" Aluminum rims" },
        { title: "Under-mounted spare tire" },
        { title: "Rear camera prep" },
      ] },
    ],
    options: [
      { title: "NPS – 6,000 watt generator with built in pure sign inverter, gas/C.A.R.B certified w/ remote" },
      { title: "Second A/C" },
      { title: "3-season removable garage wall" },
      { title: "Overlander 2 Solar Package: 400 watts of solar, MPPT 30-amp solar controller and 1800W inverter)" },
    ],
  },
  'seneca': {
    packages: [
      { name: "Customer Value Package", status: "Mandatory", items: [
        { title: "JRide® Premium: Computer-balanced driveshaft, rear air suspension, heavy-duty rear stabilizer bar, full air brakes, SACHS shocks" },
        { title: "One-piece, seamless, fiberglass front and rear caps" },
        { title: "Automotive-bonded, panoramic window in front cap with power shade" },
        { title: "Lippert™ 4000 series dual-pane frameless bonded windows" },
        { title: "2 15,000 BTU A/C units with heat pump on main A/C" },
        { title: "Electric patio awning with LED lights" },
        { title: "2,000W pure sine wave inverter" },
        { title: "Power cord reel with 50-amp service" },
        { title: "Sony® infotainment center with tilt/swivel, Apple CarPlay® and Android Auto™" },
        { title: "Backup and side-view cameras" },
        { title: "Residential refrigerator" },
        { title: "Convection microwave oven" },
      ] },
    ],
    options: [
      { title: "Power theater seating", note: "Standard on 37M", only: ["37l"] },
      { title: "Hide-a-bed sofa in place of theater seating", only: ["37m"] },
      { title: "Combination washer/dryer", only: ["37l", "37m"] },
      { title: "Stackable washer/dryer", only: ["37k"] },
      { title: "Starlink satellite internet system with KING Jack™ antenna in place of Winegard Connect 2.0" },
      { title: "Canadian Shaw® TRAV’LER® satellite dish" },
      { title: "Winegard® TRAV’LER® satellite dish - DIRECTV®" },
      { title: "Slide-out tray with 12V refrigerator cooler in basement" },
    ],
  },
  'seneca-prestige': {
    packages: [
      { name: "Customer Value Package", status: "Mandatory", items: [
        { title: "JRide® Premium: Computer-balanced driveshaft, rear air suspension, heavy-duty rear stabilizer bar, full air brakes, SACHS shocks" },
        { title: "Dual-pane, tinted, safety-glass windows" },
        { title: "Roof-mounted Girard® patio awning with LED lights" },
        { title: "2,000W pure sine wave inverter" },
        { title: "Power cord reel with 50 amp service" },
        { title: "Aqua-Hot® 250D hydronic water and heating system with 5 in. LED screen" },
        { title: "9 in. Sony® infotainment center with Apple CarPlay® and Android Auto™" },
        { title: "Backup and side-view cameras" },
        { title: "Stainless steel residential refrigerator" },
        { title: "Flush-mounted convection microwave with air fryer function" },
      ] },
    ],
    options: [
      { title: "Freezer option", only: ["37k"] },
      { title: "Power theater seating", only: ["37l"] },
      { title: "Hide-a-bed sofa", only: ["37m"] },
      { title: "Freestanding table with 4 chairs", 'except': ["37l"] },
      { title: "Stackable washer/dryer" },
      { title: "Starlink satellite internet system" },
      { title: "Winegard® TRAV’LER® satellite dish - DIRECTV®" },
      { title: "Winegard® TRAV’LER® satellite dish - Dish Network®" },
      { title: "Canadian Shaw® TRAV'LER® satellite dish" },
    ],
  },
  'seneca-xt': {
    packages: [
      { name: "Customer Value Package", status: "Mandatory", items: [
        { title: "JRide® Premium: Computer-balanced driveshaft, heavy-duty front and rear stabilizer bars, Koni® shocks" },
        { title: "15,000 BTU A/C unit with heat pump and second 13,500 BTU A/C unit" },
        { title: "2,000W pure sine wave inverter" },
        { title: "400W solar panel with dual controller" },
        { title: "Starlink satellite internet system" },
        { title: "JBL® Interior audio system" },
        { title: "2 in. BDS radius arm front suspension lift" },
        { title: "JBL® Exterior speakers, with Smart TV and Bluetooth® receiver" },
        { title: "Full-body paint" },
        { title: "Slideout topper awning(s)" },
        { title: "Powered cord reel" },
      ] },
    ],
    options: [
      { title: "Power theater seating" },
      { title: "Combination washer/dryer", only: ["35l"] },
      { title: "12V Refrigerator" },
    ],
  },
  'swift': {
    packages: [
      { name: "Customer Value Package", status: "Mandatory", items: [
        { title: "JRide®: Hellwig helper springs, premium heavy-duty suspension" },
        { title: "Electric patio awning with LED light strip" },
        { title: "Truma Combi G Comfort Plus water heater and furnace" },
        { title: "6-way adjustment driver and passenger seats" },
        { title: "2,000W inverter" },
      ] },
    ],
    options: [
      { title: "50.5 in. x 79.5 in. pop-top", only: ["20e", "20l"] },
      { title: "2 additional cab seats with slide and recline features in place of bench seat", only: ["20e", "20l"] },
      { title: "200W roof-mounted solar panel with integrated control panel", note: "Not available with pop-top option" },
      { title: "250W roof-mounted solar panel with integrated control panel", note: "Pop-top option only" },
    ],
  },
  'terrain': {
    packages: [
      { name: "Customer Value Package", status: "Mandatory", items: [
        { title: "JRide®: upgraded shocks, heavy-duty rear stabilizer bar" },
        { title: "Electric patio awning with LED light strip" },
        { title: "Roof rack and side-mounted ladder" },
        { title: "Front and rear wind deflectors with front rotating LED light bar" },
        { title: "Timberline hydronic heating system" },
        { title: "18,000 BTU variable speed air conditioner" },
        { title: "Black aluminum wheels with all-terrain 245/70R17 tires" },
      ] },
    ],
    options: [
      { title: "Rear spare tire with tire mount" },
      { title: "Driver side \"Single\" Seat", only: ["19y", "19yg"] },
    ],
  },
};
